- help/default/html/autotype.html
- src/core/PWSAuxParse.cpp
- src/os/KeySend.h
- src/os/linux/KeySend.cpp
- src/os/linux/xsendstring.cpp
- src/os/linux/xsendstring.h
- src/os/mac/KeySend.cpp
- src/os/mac/macsendstring.cpp
- src/os/mac/macsendstring.h
- src/os/windows/KeySend.cpp
- src/ui/wxWidgets/mainEdit.cpp
I have been using this code for some time now and works well on Linux.  I squashed all the changes from linux-autotype-fixes branch in master.  Also added documentation :-)
Squashed commit of the following:
commit 2a70e17f92f48ec23955aa00780eb5fb2681a7d7
Author: saurav <sauravg@users.sf.net>
Date:   Thu Aug 27 16:24:31 2015 +0530
Update docs with new autotype meta-characters
commit 39d69500e37482318d248f447ccfeabffa4043fb
Author: saurav <sauravg@users.sf.net>
Date:   Mon Aug 17 12:23:22 2015 +0530
Add dummy methods to windows/Keysend.cpp to keep compiling
commit c0b0112f81760f9308d9dba1ef18a82946f9f586
Author: saurav <sauravg@users.sf.net>
Date:   Wed Aug 12 12:44:19 2015 +0530
Remove whitespace diffs
commit c4cc471d1153d789f6c9113946023852894bcefd
Author: Saurav Ghosh …
> Autotype fixes for conflicts with browser autofill

- src/core/Makefile
- src/os/linux/Makefile
- src/ui/wxWidgets/Makefile
0.95 and later fails to build from source on Debian systems.  Enabling position independent code (-fPIC) resolves the issue.
> Generate position independent code.  This fixes FTBFS on Debian

- src/core/BlowFish.cpp
- src/core/BlowFish.h
- src/core/Fish.h
- src/core/ItemData.cpp
- src/core/ItemData.h
- src/core/ItemField.cpp
- src/core/ItemField.h
- src/core/TwoFish.cpp
- src/core/TwoFish.h
This includes two commits for performance enhancements.
The first one https://github.com/pwsafe/pwsafe/commit/b88f60487806bcfddf2e22846e6622d7a470db8e simply adds syntax changes to avoid useless virtual indirection in leaf classes and adds const markers to the encryptors methods which effectively do not change its internal state. This last change will be needed on the next commit.
The second one https://github.com/pwsafe/pwsafe/commit/198b6cdb33d3dc501220c557252794bab5df54f6 has been made due to a finding in the profiler, which showed that most of the CPU time spent opening huge safes was creating and destroying equivalent Blowfish objects. On an iPhone 4s this change make a 1500-entries safe open in 0,5 seconds instead of 2,5, which is a huge UX gain.
> Encryption Changes

- CodeLite/exec-wx3-config
- CodeLite/pwsafe.project
- src/ui/wxWidgets/PasswordSafeSearch.cpp
Only 233c37c is required to fix the focus issue.  The rest are required to build with CodeLite IDE (I guess I alone use it).
> 1193: Ctrl-F would set focus to search textbox if searchbar is already visible

- src/ui/wxWidgets/PasswordSafeSearch.cpp
Don't hide "find..." menu item while searching
The only reason wxWidgets sends us Activate event on Mac on
hitting Cmd-F is that menu item. If it is removed, wxWidgets
won't generate Activate events on Mac anymore and Cmd-F will
do nothing until we close and re-open the search bar.
I have no idea why this isn't an issue on Linux as well.
> Part 2 of searchbar focus fix: for OSX

- src/ui/wxWidgets/TimedTaskChain.cpp
- src/ui/wxWidgets/optionspropsheet.cpp
64057c2 - fix for the heap overflow (hopefully)
884e164 - fix for the assert of osx if wxCB_SORT is used
> Fix for the heap overflow in TimedTaskChain and for a nasty assert on osx

- src/ui/wxWidgets/pwsmenushortcuts.cpp
Replace deprecated API usages to more modern for wxWidgets 3.0
- wxEVT_GRID_CELL_CHANGE -> wxEVT_GRID_CELL_CHANGED
- wxGrid::GetCursorRow() -> wxGrid::GetGridCursorRow()
Now pwsafe can be built with wxWidgets without 2.8 compatibility
Tested on Mac with wxWidgets from master branch (because stable 3.0.2 doesn't compile on El Capitan).
> Modernize old wxWidgets 2.8 APIs

- src/ui/wxWidgets/PasswordSafeSearch.cpp
- src/ui/wxWidgets/passwordsafeframe.cpp
wxEXPAND conflicts with wxALIGN_* sizer flags. Use only wxEXPAND for layout sizers.
> Fix couple assertions in sizer code.

- src/ui/wxWidgets/safecombinationentry.cpp
- src/ui/wxWidgets/safecombinationentry.h
wxWindow->SetFocus on Mac OS X works only if window already visible on screen.
So:
- move code for autoselect the master password field to EVT_ACTIVATE event handler for the dialog.
- guard the code to be called only once (in case user will change focus and switch between applications).
> Fix autofocus on master password field in the startup dialog on Mac.

- src/ui/wxWidgets/passwordsafeframe.cpp
- src/ui/wxWidgets/passwordsafeframe.h
- src/ui/wxWidgets/pwsafeapp.cpp
Issue #45
When using the -s switch, don't show the main window. This fixes the problem of the main window sometimes remaining visible when the program starts.
If the systray is being used, show the tray icon after all other initialization is done. This insures the tray icon's visible from the start even if the main window is never shown, rather than only being shown after the main window is closed for the first time.
> Fix window visibility on initial open, fix showing of system tray icon

- src/ui/Windows/PWTreeCtrl.cpp
- src/ui/Windows/PWTreeCtrl.h
Note: Only tested D&D within the same instance so far but might work between instances too.
> Fix D&D involving Empty Groups

- src/os/mac/file.cpp
Parallel other use of 'statbuf' rather than 'info' in
::(fn, &statbuf)
As described in [Ticket #1321](https://sourceforge.net/p/passwordsafe/bugs/1321/), *src/os/mac/file.cpp* does not compile under Mac OS X 10.11.2 with Xcode 7.2
* *&statbuf* is not defined
* *status* is declared twice
This change allows this specific file to compile.
Not that I cannot yet verify the functionality as the project does not successfully build. *Generate version.h* does not appear to run, causing problems with *About.cpp* missing *version.h*
> Fix errors in ::GetFileTimes for Mac OS X

- src/os/CMakeLists.txt
When I try to build project on Linux with cmake
```sh
mkdir build && cd build
cmake -GNinja -DNO_YUBI=YES ..
```
, it failed to compile `src/os/linux/PWYubi.c`. `src/os/linux/Makefile` has logic to exclude this file from build with yubikey support disabled.
So this patch implement same logic for cmake build.
> Fix cmake build on Linux without yubikey lib (NO_YUBI option)

- src/os/CMakeLists.txt
Commit e12b2f64717efa18589784f78894303ebaedf2a5 included a typo that resulted in a failing build of pwsafe with Yubikey support on Linux.
> Fix cmake build on Linux with yubikey lib

- Misc/unicode2keysym.pl
- src/os/linux/unicode2keysym.cpp
1. No need to use a C++ map. A switch/case statement is good enough, and faster.
2. Ignores the deprecated mappings if they are superceded by anything else.
3. Includes a few new keysyms from the latest X11/keysymdefs.h
> Simpler, faster and more accurate wchar => keysym map

- Makefile.linux
- src/test/Makefile
* Automatically build gtest lib in-tree during build (instead of
requiring it be manually built beforehand)
* Allow test build/run for release builds
* Add test dir to top-level clean targets
> gtest-related makefile enhancements:

- CodeLite/PasswordSafe.workspace
- CodeLite/core.project
- CodeLite/os.project
- CodeLite/pwsafe.project
- src/core/PWSprefs.cpp
- src/core/PWSprefs.h
- src/os/linux/KeySend.cpp
- src/os/linux/xsendstring.cpp
- src/os/linux/xsendstring.h
This fixes autotype for those keyboard layouts where additional symbols are generated by pressing the modifier key corresponding to ISO_Level3_Shift:
https://sourceforge.net/p/passwordsafe/bugs/1281/
Its a pretty big rewrite that simplifies the XWindows autotype logic greatly, making the code easily extensible and maintainable, at a slight (mostly theoretical & unnoticeable) cost to efficiency.
> Fix autotype for level3+ keysyms: German Autotype Fix

- docs/ReleaseNotes.html
- docs/ReleaseNotes.txt
- src/core/CoreImpExp.cpp
- src/core/PWScore.cpp
- src/core/PWScore.h
- src/core/coredefs.h
- src/ui/Windows/ManagePSWDPols.cpp
- src/ui/Windows/ManagePSWDPols.h
- src/ui/Windows/PWPListEntries.cpp
- src/ui/Windows/PWPListEntries.h
- src/ui/Windows/PasswordSafe.rc
- src/ui/Windows/pwsafe-12.vcxproj
- src/ui/Windows/pwsafe-12.vcxproj.filters
- src/ui/Windows/pwsafe-14.vcxproj
- src/ui/Windows/pwsafe-14.vcxproj.filters
- src/ui/Windows/res/PasswordSafe2.rc2
- src/ui/Windows/res/PasswordSafe3.rc2
- src/ui/Windows/resource.h
- src/ui/Windows/resource2.h
- src/ui/Windows/resource3.h
Whilst implementing FR 806, found & fixed bug re: export of named password policies to XML. Then decided I needed a way to easily see what entries used a partiular named password policy and so implemented it as a FR.
Note: only tested under VS2015. VS2013 files edited manually as I have now standardised on VS2015 and uninstalled VS2013.
> Fix export of Named Password Policies to XML and implement FR to view associated entries

- CMakeLists.txt
see issue #85 for more explanations.
> fix cmake/wx win32 in non-win32 section, hint on wx-config usage from command-line

- src/os/linux/pws_time.cpp
gmtime64_s is expecting gmtime64_r to return true on success, false on failure.
gmtime64_r is returning ( gmtime_r() ==  0), but gmtime_r returns pointer to struct on success or NULL on error.  So it appears that the check in gmtime64_r is backwards.
> Logic mismatch between gmtime64_r/gmtime_r and gmtime64_s

- src/test/Makefile
Reorder libs so uuid comes after other libs that require it
> Patch from Ubuntu to fix link failure when built with -Wl,--as-needed

- src/ui/Windows/I18N/pos/pwsafe_de.po
Included a white space in the German translation.
> Included space in German translation.

- Xcode/pwsafe-xcode6.xcodeproj/project.pbxproj
Misc/mkversion.pl has changed and now expects some additional args.
Without those, it won't generate version.h. We pass some dummies
to keep it happy.
> Fix osx builds done using Xcode

- CMakeLists.txt
Hi,
Please, consider to merge my pull.
With this pull, I'm trying to fix these two issues (see #122):
1. The CPack problem that generates a bad RPM which conflicts with the `filesystem` package.
2. The location of `pwsafe.desktop` and `pwsafe.png`.
Regarding the last point, I'm not sure if my fix conflicts with other non-RPM-based environment.
Unfortunately, I didn't find an easy way to tell CPack to copy these files in the new locations only if the generator is RPM.
That is, a safer fix would be:
```
if(CPACK_GENERATOR MATCHES "RPM")
install (FILES "install/desktop/pwsafe.desktop" DESTINATION "share/applications")
install (FILES "install/graphics/pwsafe.png" DESTINATION "share/pixmaps")
else ()
install (FILES "install/desktop/pwsafe.desktop" DESTINATION "share/pwsafe")
install (FILES …
```
> Fix rpm spec

- src/core/StringX.h
- src/core/Util.cpp
On Mac OS X 10.11 (clang), StringX's deallocation function uses a series of memset to securely scrub out sensitive memory after usage. Clang can optimize the memset()'s out completely leaving sensitive data in memory. I put together a test case:
```
#include <string>
#include "StringX.h"
extern StringX getXX();
void testGccStringXOptimization()
{
StringX secureString = getXX();
printf("%s\n", secureString.c_str());
// <- check assembly to see if memset() is called
}
```
and on my machine (Apple LLVM version 7.3.0 (clang-703.0.31)):
```
__Z26testGccStringXOptimizationv:       ## @_Z26testGccStringXOptimizationv
Lfunc_begin0:
.file	39 "/Users/sound/Desktop/pwsafe/src/os" "d.cpp"
.loc	39 14 0                 ## /Users/sound/Desktop/pwsafe/src/os/d.cpp:14:0
.cfi_startproc
pushq	%rbp
Ltmp0: …
```
> StringX's deallocate memset()'s can get optimized out by the compiler on gcc/clang

- CMakeLists.txt
- README.FREEBSD
- src/os/CMakeLists.txt
- Include /usr/local/include so we can find uuid/uuid.h
- Tested on 10.3
- Update requirements and instructions
- Share the same source files a Linux builds
> Update to build via cmake on FreeBSD 10.3-RELEASE

- docs/formatV3.txt
- docs/formatV4.txt
Currently unimplemented in PasswordSafe, but defined for use in a
compatible program.
> Added QR code entry field in v3 and v4.

- src/Tools/Windows/I18N/ResText/ResModule.cpp
- src/Tools/Windows/I18N/ResText/ResModule.h
- src/Tools/Windows/I18N/ResText/ResText.cpp
This flag is useful when checking for untranslated entries (msgid will be printed to stderr).
> Added (restored) 'showdefault' flag for ResText tool

- Xcode/generate-configs
- Xcode/pwsafe-xcode6.xcodeproj/project.pbxproj
This fixes #188
- Added '-L/usr/local/lib' to the linker flags
- Added 'passwordsubsets.{cpp,h}' to a Xcode project
> Fixes Build failure on Mac OS X

- src/ui/Windows/ThisMfcApp.cpp
otherwise encrypt/decrypt dialog and command line parameters' help aren't localized
> Load localized resources before command line processing

- README.FREEBSD
- src/core/ItemData.cpp
- src/core/ItemData.h
- src/core/PWSFilters.cpp
There are multiple functions named Matches() that differ only by
parameter type. In 32-bit BSD, the params for two of these are
both actually int. No callers are depending on the correct
overload to be bound based on type, so the easy fix is to rename one of
them, and change the call site to use the new name.
This fixes issue #196.
I built FreeBSD 32-bit and 64-bit and OS X and smoke-tested the app. I did not build Windows.
> Fix compile error on 32-bit FreeBSD

- src/ui/Windows/AddEdit_Additional.cpp
- src/ui/Windows/AddEdit_Additional.h
- src/ui/Windows/AddEdit_PropertySheet.cpp
- src/ui/Windows/MainEdit.cpp
When editing an alias, show base's PWH in AddEdit_Additional tab
Restore alias' PWH if user reverts it to a normal entry
Also rename AddEdit_Additional member function to be different to that of CItemData
> Save normal entry's PWH when becoming an alias

- docs/ReleaseNotes.html
- docs/ReleaseNotes.txt
- src/core/PWSFilters.cpp
- src/core/PWSFilters.h
- src/core/PWScore.h
- src/ui/Windows/DboxMain.cpp
- src/ui/Windows/MainView.cpp
- src/ui/Windows/PWFindToolBar.h
- src/ui/Windows/PWTreeCtrl.cpp
1. All empty groups are no longer shown when the user filters for only entries with expired passwords.
2. Empty groups added but not yet saved are now included when the user filters on unsaved changes.
3. Empty groups, whose names satisfy a filter that include tests on group name values, are now included in the display when the filter is active.
> Resolve various empty group/filter issues:

- help/default/html/autotype.html
- src/core/Command.cpp
- src/core/PWSAuxParse.cpp
- src/core/PWScore.cpp
- src/core/PWScore.h
- src/ui/Windows/DboxMain.cpp
- src/ui/Windows/DboxTray.cpp
- src/ui/Windows/EditShortcutDlg.cpp
- src/ui/Windows/MainEdit.cpp
- src/ui/Windows/MainView.cpp
- src/ui/Windows/PWTreeCtrl.cpp
I have made PWS consistent throughout wrt username and shortcuts. I have also backed out BR1124 but via an #ifdef/#else/#endif.  As it stands, BR1124 is undefined in the project.  Depending on your decision, you can either define it (not recommended), swap the code around and change #ifdef to #ifndef to re-instate BR1124 consistently or remove the #ifdef/#else#/endif and make the change you want permanent.  Search on BR1124 over the entire solution.
> Some more fixes

- src/test/coretest-14.vcxproj
Without this set, VS2017 RC can't convert the project.
Also, as dropped XP support, remove it from coretest too.
> Set coretest target platform to match that of pwsafe.

- src/ui/Windows/MainEdit.cpp
- src/ui/Windows/MainManage.cpp
- src/ui/Windows/MainView.cpp
Detected by new VS2017 RC whilst fixing 122 new warnings C4840 generated by new compiler
VS2017 C4840 recommended workaround not included yet
> Fix CString format errors when using StringX variables

- src/ui/wxWidgets/PWSDragBar.cpp
- src/ui/wxWidgets/addeditpropsheet.cpp
- src/ui/wxWidgets/dragbar.h
- src/ui/wxWidgets/passwordsafeframe.cpp
- src/ui/wxWidgets/passwordsafeframe.h
Attempt to fix D'n'D from Dragbar for alias/shortcut items: tried to use the same checkers/getters as in MFC ver. (haven't found quick and clean way without adding PasswordSafeFrame::GetBaseEntry).
Also quick and dirty fix for Add/Edit dialog, to show "base reference" for Alias entries (without check for alias correctness and other alias/shortcuts improvements, that were recently added to MFC version).
> [wx] few fixes for alias/shortcut entries

- src/core/Command.cpp
- src/core/Command.h
- src/core/CoreImpExp.cpp
- src/core/CoreOtherDB.cpp
- src/core/Item.cpp
- src/core/Item.h
- src/core/PWScore.cpp
- src/core/PWScore.h
- src/core/UIinterface.h
- src/core/XML/XMLFileHandlers.cpp
- src/ui/Windows/DboxMain.cpp
- src/ui/Windows/DboxMain.h
- src/ui/Windows/DboxTray.cpp
- src/ui/Windows/MainEdit.cpp
- src/ui/Windows/MainFile.cpp
- src/ui/Windows/MainFilters.cpp
- src/ui/Windows/MainMenu.cpp
- src/ui/Windows/MainView.cpp
- src/ui/Windows/PWTreeCtrl.cpp
- src/ui/Windows/ThisMfcApp.cpp
- src/ui/wxWidgets/PwsSync.cpp
- src/ui/wxWidgets/mainEdit.cpp
Also, as Execute, Redo, Undo were virtually identical - merge into one routine.
> Remove GUI info from core

- src/os/mac/file.cpp
This is a minor change to fix a build error on Xcode 8.2.1.
> Fix build error on macOS 10.12.3 with Xcode 8.2.1

- README.WINDOWS.DEVELOPERS.html
- pwsafe-14.sln
- src/core/core-14.vcxproj
- src/core/core_wx-14.vcxproj
- src/os/windows/os-14.vcxproj
- src/os/windows/os_wx-14.vcxproj
- src/os/windows/pws_autotype/pws_autotype-14.vcxproj
- src/os/windows/pws_osk/pws_osk-14.vcxproj
- src/os/windows/yubi/YkLib22-14.vcxproj
- src/os/windows/yubi/YkLib22_wx-14.vcxproj
- src/test/coretest-14.vcxproj
- src/ui/Windows/language/languageDLL-14.vcxproj
- src/ui/Windows/pwsafe-14.vcxproj
- src/ui/wxWidgets/pwsafe_wx-14.vcxproj
Update  VS2015 projects (MFC & wx) & Windows' Developer Readme for 64-bit builds.
Note: This does not fix any warnings or errors in the build and coretest does not link in DebugM 64-bit.
> Update projects to enable coexistence of x86 & x64 builds

- src/core/CoreImpExp.cpp
- src/core/ItemAtt.cpp
- src/core/ItemData.cpp
- src/core/PWScore.cpp
- src/core/PWSfileV4.cpp
- src/core/PWSfileV4.h
- src/core/VerifyFormat.cpp
- src/os/file.h
- src/os/windows/file.cpp
- src/os/windows/mem.cpp
- src/ui/Windows/AddEdit_Additional.cpp
- src/ui/Windows/AddEdit_Attachment.cpp
- src/ui/Windows/AddEdit_Basic.cpp
- src/ui/Windows/DboxMain.cpp
- src/ui/Windows/MainEdit.cpp
- src/ui/Windows/MainFile.cpp
- src/ui/Windows/MainMenu.cpp
- src/ui/Windows/MainView.cpp
- src/ui/Windows/OptionsShortcuts.cpp
- src/ui/Windows/PWFindToolBar.cpp
- src/ui/Windows/PWListCtrl.cpp
- src/ui/Windows/PWSFaultHandler.cpp
- src/ui/Windows/PWTreeCtrl.cpp
- src/ui/Windows/PasskeyChangeDlg.cpp
- src/ui/Windows/SCWListCtrl.cpp
- src/ui/Windows/ViewAttachmentDlg.cpp
- src/ui/Windows/filter/ManageFiltersDlg.cpp
- src/ui/Windows/filter/PWFilterLC.cpp
This set of changes resolves all of the compiler warnings (known as of this instant in time) that were produced when building DebugM/ReleaseM x64 builds under VS2015. The changes were checked in both x86 and x64 builds.
A good number of the warnings came from the use of the size_t data type. In x86 size_t is a 32 bits, but in x64 it is 64 bits. Developers working in x64 builds need to be cognizant of this detail. It would be easy to create a situation where incompatibilities were introduced by using a size_t variable in a data structure and then writing the data structure to a file.
Developers working on VS2015 should probably build both x86 and x64 configurations to verify that they have not introduced any compiler warnings.
> gh270b - VS2015 compiler warnings for DebugM/ReleaseM x64 build

- src/os/windows/pws_autotype/pws_autotype-14.vcxproj
- src/os/windows/pws_osk/pws_osk-14.vcxproj
- src/ui/Windows/language/languageDLL-14.vcxproj
- src/ui/Windows/pwsafe-14.vcxproj
Tidy up parameters making as much as possible the same for all platforms by using predefined variables $(OutDir) & $(IntDir)
> Fix lack of Debug symbols in new project structure

- src/ui/Windows/AddEdit_Basic.cpp
- src/ui/Windows/AddEdit_PropertySheet.cpp
This small change fixes two compiler warnings that occur in VS 2015 x64 builds.
> Fix two 64-bit build compiler warnings.

- src/ui/Windows/I18N/Create_DLLs.vbs
- src/ui/Windows/I18N/Translations.vbs
- src/ui/Windows/I18N/Update_POs.vbs
This set of changes reworks Update_POs.vbs to make it work like Create_DLLs.vbs. Now both are driven by the list of available translations in the Translations.txt file. With this change, neither Update_POs.vbs nor Create_DLLs.vbs has to be changed to add a new translation (juste add a new record to Translations.txt).
Common VB script code used by Create_DLLs and Update_POs was moved
into Translations.vbs.
> Rework Update_POs.vbs to use the Translations.txt file.

- CodeLite/os.project
- CodeLite/pwsafe.project
- src/os/unix/KeySend.cpp
- src/os/unix/Makefile
- src/os/unix/keyname.cpp
- src/ui/cli/Makefile
To let it build and run in headless environments. Otherwise, in some cases, it might require one to build X itself first.
> Avoid linking pwsafe-cli with X libraries

- src/test/Makefile
The autotools-based makefile for the test driver is missing LDFLAGS for the X11 and Xtst libs, causing linking to fail on Debian.  In addition, it does not honor LDFLAGS passed in from the build process.
> Test Makefile Fixes

- CodeLite/pwsafe.project
- README.LINUX.DEVELOPERS.txt
- src/ui/wxWidgets/Makefile
- src/ui/wxWidgets/mainEdit.cpp
- src/ui/wxWidgets/passwordsafeframe.cpp
- src/ui/wxWidgets/passwordsafeframe.h
- src/ui/wxWidgets/pwsqrcodedlg.cpp
- src/ui/wxWidgets/pwsqrcodedlg.h
Add an item to the popup menu brought up by right-clicking an item to show the entry's password as a QR code. For security reasons, the dialog closes automatically after 15 seconds.
This is useful for quickly transferring a password to a mobile device securely using a [QR-code scanning app](https://play.google.com/store/apps/details?id=com.google.zxing.client.android&hl=en)
Cons: adds yet another build dependency: libqrencode
Currently its linux-only. Stil researching on osx.
> Add a feature to display a password as QR code

- help/default/html/security_tab.html
with information about the specifics of the key stretching. If I see right PBKDF2 isn't yet used, if it is, the PR shall be slightly modified (unless the iteration numbers would differ).
> Help: update security+settings 

- src/core/PWSfileV1V2.cpp
Add additional call to mbstowcs to check needed size prior to allocating
buffer.  Related to issue #367 
Note: mbstowcs calls OS specific code.  I have NOT tested this on Windows, but a review of the MSDN docs on MultiByteToWideChar leads me to believe it's OK.  Someone with a Windows machine should verify.
> Fix mbstowcs-related heap overflow

- src/test/CommandsTest.cpp
According to the V3 spec and the comments in CItemData::UpdatePassword,
the password expiration interval should be specified in days.  However
the test for UpdatePasswordCommand was setting it in seconds since epoch.
This lead to sign flipping on 32-bit systems which resulted in test failure.
> Fix UpdatePasswordCommand test to use correct units

- src/ui/wxWidgets/passwordsafeframe.cpp
This fixes a cosmetic problem with the dragbar.
Currently, just after unlocking a safe the dragbar appears as expected:
Widening the passwordsafe window does not also widen the dragbar:
> Expand and shrink dragbar with the main frame

- src/ui/wxWidgets/wxutils.cpp
The function wxLinuxDistributionInfo is only available on Linux. Add check for LINUX symbol as per [documentation](http://docs.wxwidgets.org/3.0/group__group__funcmacro__networkuseros.html#ga06f6fb212c396bd20865ee4e2f69aa1f)
`This function is Linux-specific and is only available when the LINUX symbol is defined. `
> Unbreak build on FreeBSD

- CMakeLists.txt
Small re-order.  Build target referenced before being defined when IPO support is available. 
Necessary fix to compile under [Arch] Linux.
> cmake build fix for IPO support

- src/ui/wxWidgets/addeditpropsheet.cpp
This change makes the text entry fields of the properties sheet expandable so that they get more available space. This makes more content of the text fields visible.
Layout without this change:
Layout after applied change:
> Make text entry fields of properties sheet expandable

- src/ui/wxWidgets/addeditpropsheet.cpp
If a default username is set in preferences it gets
shown in wx based dialog for adding a new user.
This addresses the second part of issue #148.
> Show default user name from preferences

- src/ui/wxWidgets/pwsafeapp.cpp
- src/ui/wxWidgets/pwsafeapp.h
Calling the Help from a modal dialog broke the applications event handling.
> Fix help system of wx based variant of PWSafe

- src/ui/wxWidgets/I18N/pos/pwsafe_de.po
- src/ui/wxWidgets/optionspropsheet.cpp
- src/ui/wxWidgets/safecombinationentry.cpp
The translation enabling of string literals that are part of an array is based on the wx API documentation (see [here](http://docs.wxwidgets.org/3.0/group__group__funcmacro__string.html#gab8862de0f74049708bfea75ae9e14c45) and [here](http://docs.wxwidgets.org/3.0/group__group__funcmacro__string.html#ga8a02b8875a521df57263a9e6f090f2d0)).
Textfields, that are intended to show a user selected path, are now stretchable, hence got more width to show more of the path.
> Enable translation for comboboxes and improve layout of options dialog

- CMakeLists.txt
- help/CMakeLists.txt
- install/slackware/.gitignore
- install/slackware/passwordsafe.SlackBuild
I've updated SlackBuild to use cmake, also there are few fixes for wx help archives built with CMake:
- temporary CMakeFiles directory was included into help archive;
- wx (at least in linux) wants to have `/` instead of `\` in path to files inside hhc/hhk/hhp, so I've added conversion step (but maybe it'll be better to use `/` in original hhc/hhk/hhp, hhw/hhc should support it too)
> Updates for SlackBuild / CMake

- src/core/PWSprefs.cpp
- src/ui/wxWidgets/pwsafeapp.cpp
Eliminates some "invalid read of size" issues, caused by 
function wcstombs on access to wide character sequences.
> Prevent possible string conversion issues with wcstombs

- src/ui/wxWidgets/PWStree.cpp
- src/ui/wxWidgets/PWStree.h
Fixes the reported issue #1426 on Sourceforge.
Now, left arrow key collapses a selected group or 
moves the selection up to the next item in the tree.
> Fix #1426 "Linux, Tree View: Arrow key Behavior Not as Expected"

- src/core/BlowFish.cpp
- src/core/ItemData.cpp
- src/core/PWSfileV3.cpp
- src/core/PWSfileV4.cpp
- src/core/Util.cpp
- src/core/Util.h
- src/os/unix/pws_time.cpp
While passwordsafe compiles on big-endian architectures, many of the tests fail, and the program is unusable.
I've found the causes of the test failures and attempted to address them.  More details about the specific changes are in the individual commit messages.  I'd of course be happy to answer any questions, or to receive feedback/suggestions.
These changes were tested on s390x (64-bit) and mips (32-bit) running Linux.  With these changes, all tests pass.
I also verified that these changes didn't cause breakage on my little-endian (Linux on amd64) system.
I don't have a windows system to test against, but expect it to be fine, as the changes are either ifdef wrapped for big-endian systems or are changes that *should* cause issues in Linux and Windows equally if they were to occur.
> Fixes for Big-Endian Architectures

- src/ui/wxWidgets/passwordsafeframe.cpp
- src/ui/wxWidgets/passwordsafeframe.h
These modifications prevent the creation of a new status bar on top of the already existing one if the language is switched. Hence, the status bar is only created once from within PasswordSafeFrame::Create.
> Prevent creation of status bar on language switch

- src/ui/wxWidgets/ManagePwdPolicies.cpp
- src/ui/wxWidgets/ManagePwdPolicies.h
1. Exisitng rows of grid showing policy details are reused now, instead of always adding new rows.
2. Grid columns are using more of the available space and resizing correctly when dialog's size changes.
> Some minor improvements to the policies dialog

- src/os/unix/dir.cpp
pws_os::getenv already ensures that directory path ends with a slash.
Adding a slash in 'createuserprefsdir' leads to have two slashes
between the home and preferences directory.
> Prevent adding an additional slash to users preferences directory

- src/ui/Windows/OptionsSecurity.cpp
Without update of `m_HashIter` on `PP_DATA_CHANGED` query, Preferences dialog incorrectly report about unsaved changes after canceling.
Also is seems to be right to update `m_HashIter` on any `UpdateHashIter` call, and use `MinHIslider` instead of hardcoded `0`.
> Update m_hashIter on slider set and before check for changes

- Makefile.linux
When building with autotools, certain makefiles set compiler flags based
on the CONFIG value, which may be different from the build target. This
can lead to a "release" build being built with DEBUG defined.  This
can cause issues locating the help files, among other things.
This patch sets the CONFIG param for all sub-makefiles.
Tested on Debian 9.
> Fix mixed release/debug autotools builds

- src/ui/wxWidgets/passwordsafeframe.cpp
- src/ui/wxWidgets/passwordsafeframe.h
- Added new menu items (Lock Safe/Unlock Safe) under menu item 'Edit'
if taskbar icon is not available (see issue [#1443](https://sourceforge.net/p/passwordsafe/bugs/1443/) at SourceForge).
- Menu items 'Lock Safe', 'Unlock Safe' and 'Password Policies' are
enabled and disabled depending on DB state.
- Related to reported issue [#446](https://github.com/pwsafe/pwsafe/issues/446) on GitHub.
> Add menu items for lock/unlock of DB

- src/ui/wxWidgets/I18N/pos/pwsafe_de.po
- src/ui/wxWidgets/safecombinationsetup.cpp
- Text fields of 'safecombinationsetup' dialog are now expandable to get available space
- The german text took too much space due to missing newline character so that dialog didn't look nice
- Centered buttons
- Added more gap between frame border and controls
**The original version with German text**
**The modified version with German text**
**The modified version with English text**
**The modified version with expandable text fields**
> Layoutimprovements of safecombinationsetup dialog

- src/os/file.h
- src/os/unix/file.cpp
- src/ui/wxWidgets/ExternalKeyboardButton.cpp
If xvkbd (virtual keyboard) doesn't exist on users PC wxExecute still returns with a valid PID, which might be a [bug](http://wxwidgets.10942.n7.nabble.com/Asynchronous-wxExecute-failure-reporting-td78084.html) in the Wx framework. From the users perspective nothing points to the reason why the virtual keyboard doesn't appear, which looks like a problem of Password Safe. There are already two tickets on SourceForge referring to a not appearing virtual keyboard.
- [#930](https://sourceforge.net/p/passwordsafe/bugs/930/) Virtual keyboard doesn't work on Debian Linux
- [#944](https://sourceforge.net/p/passwordsafe/bugs/944/) Virtual keyboard not appearing
> Add check for virtual keyboard (xvkbd)

- src/ui/wxWidgets/passwordsafeframe.cpp
This prevents an assertion on maximize/restore if safe was closed previously.
> Prevent lock/unlock if no safe is open

- src/os/unix/Makefile
The os/unix makefile hardcodes the name of the pkg-config utility, which
prevents cross-compiling on some systems.
Forwarded from https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=901092
> Don't hardcode pkg-config in Makefile

- src/core/Makefile
- src/test/Makefile
The inclusion of WX calls in core required changes to the core and test
makefiles in order to successfully build without using cmake
> Fix non-cmake-based build

- src/ui/wxWidgets/optionspropsheet.cpp
- src/ui/wxWidgets/optionspropsheet.h
- Move some logic for enabling/disabling of controls from specific event handlers to OnUpdateUI.
- Fix disabling of some controls at 'Password History' and 'System' tab.
- Remove disabling of some controls in R-O mode of 'System' tab, which are not DB specific.
> [wx] Correct enabling/disabling of Options dialog's controls

- src/core/PWScore.h
- src/ui/wxWidgets/mainManage.cpp
- src/ui/wxWidgets/passwordsafeframe.cpp
- src/ui/wxWidgets/pwsafeapp.cpp
This allows a more expressive check for an open database.
Example: m_core.IsDbOpen()
Replaces in the wx implementation all checks for an empty
database file name string.
Example: !m_core.GetCurFile().empty()
> [wx] Introduce IsDbOpen() to the core

- src/ui/wxWidgets/properties.cpp
- src/ui/wxWidgets/properties.h
- src/ui/wxWidgets/wxutils.cpp
- src/ui/wxWidgets/wxutils.h
- Follow implementation of review proposal (see #488) for OnEditName and OnEditDescription
- Reserve three lines of static text for DB description
- Limit DB name and DB description to the available space on UI
> Limit DB name and DB description on UI

- src/ui/wxWidgets/addeditpropsheet.cpp
Fixes reported issue [1478](https://sourceforge.net/p/passwordsafe/bugs/1478/) on SF.
> [wx] Apply configured password font in Edit/View dialog

- src/ui/wxWidgets/PasswordPolicy.cpp
- src/ui/wxWidgets/PasswordPolicy.h
- src/ui/wxWidgets/addeditpropsheet.cpp
- src/ui/wxWidgets/addeditpropsheet.h
- Width of all spinners is unified to 60 or 80 pixels depending on spinners max. value
- Value range of all spinners is set to values from preferences
- Takeover of AddEditPropSheet::OnAtLeastChars to CPasswordPolicy for an uniform behavior
> [wx] Unification of password rules dialogs

- xml/KPX0_to_PWS.xslt
was requested at SF BR 1173
as usual
- only supported autotype template placeholders are translated to pwsafe's autotype
(unknown copied to autotype string as is), also original autotype string stored at Notes,
- binary attachments are ignored (but it's description copied to Notes)
> XSLT template for KeepassX v0.4.3 XML

- src/ui/wxWidgets/addeditpropsheet.cpp
- src/ui/wxWidgets/properties.cpp
Changed alignment of some labels at Properties and Add-Edit dialog following the [guideline](https://developer.gnome.org/hig/stable/visual-layout.html.en) for visual layouts at Gnome Developer. Some dialogs (e.g. Add-Edit > Dates and Times) are already conform to that rules, so that a more consistent visual appearance is provided by this pull request.
See also discussion at [ux.stackexchange](https://ux.stackexchange.com/questions/8873/why-might-right-aligned-field-labels-be-better) regarding the advantage of right aligned labels.
> [wx] Right align labels of Properties and Add-Edit dialog

- src/ui/wxWidgets/PWSDragBar.cpp
Dragbar tooltips are constructed from a fixed translated text and a non-translated field name text. Changing the latter also to translated.
> Making dragbar tooltips translatable

- src/ui/wxWidgets/safecombinationchange.cpp
- src/ui/wxWidgets/safecombinationentry.cpp
- src/ui/wxWidgets/safecombinationprompt.cpp
Dialogs for requesting password from user are restricted to grow in width.
Changing the width of such a dialog will only change the width of the text entry fields.
This should prevent something like the following example, which looks a bit strange.
> [wx] Tweaks to layout of password dialogs

- src/os/unix/pws_time.h
Fixes #541 
Updates pws_time.h to check for existing definition of __time64_t before attempting to redefine it using a typedef.
> Fixes #541 compilation error

- CMakeLists.txt
This fixes a dependency conflict error when installing on Ubuntu. The
compile-time version is libcurl4*, so runtime one should match.
Related to https://github.com/pwsafe/pwsafe/issues/551
> Update runtime version of libcurl to match compile version

- src/ui/wxWidgets/safecombinationentry.cpp
Storing the passphrase of newly created DB prevents that loading new DB provides  *PWSfile::WRONG_PASSWORD* (because an empty passphrase was used, instead of the one the user specified for new DB) and Core's internal state (m_bIsOpen) is wrongly set.
> [wx] Store passphrase of newly created DB

- src/core/PWPolicy.cpp
- don't show assert, when only hexadecimals are selected
- new description wasn't used for pronounceable passwords
> Minor fixes for policy settings

- CMakeLists.txt
- README.LINUX.DEVELOPERS.md
Removed libqrencode-devel on README.LINUX.DEVELOPERS.md because correct one, already included, is qrencode-devel.
Update CMakeLists for a typo on RPM metadata -> file-libs inclusion.
> libmagic - update libs README.LINUX.DEVELOPERS.md and CMakeList RPM metadata

- src/ui/Windows/DboxMain.cpp
Otherwise an empty window appears briefly before exiting.
Closes: #406
> Do not show main window if user cancelled the PasskeyEntry dialog.

- Misc/I18N/ru/omegat_wx/omegat/project_save.tmx
- Misc/I18N/ru/omegat_wx/omegat_wx-level1.tmx
- Misc/I18N/ru/omegat_wx/omegat_wx-level2.tmx
- Misc/I18N/ru/omegat_wx/omegat_wx-omegat.tmx
- src/ui/wxWidgets/CryptKeyEntry.cpp
- src/ui/wxWidgets/I18N/pos/pwsafe_da.po
- src/ui/wxWidgets/I18N/pos/pwsafe_de.po
- src/ui/wxWidgets/I18N/pos/pwsafe_es.po
- src/ui/wxWidgets/I18N/pos/pwsafe_fr.po
- src/ui/wxWidgets/I18N/pos/pwsafe_hu.po
- src/ui/wxWidgets/I18N/pos/pwsafe_it.po
- src/ui/wxWidgets/I18N/pos/pwsafe_ko.po
- src/ui/wxWidgets/I18N/pos/pwsafe_nl.po
- src/ui/wxWidgets/I18N/pos/pwsafe_pl.po
- src/ui/wxWidgets/I18N/pos/pwsafe_ru.po
- src/ui/wxWidgets/I18N/pos/pwsafe_sv.po
- src/ui/wxWidgets/I18N/pos/pwsafe_zh.po
I noticed this typo while browsing through the code.  Since it's an internal string that isn't displayed anywhere, I don't suppose it matters all that much.  Regardless, here's a patch.
> Fix "Encrytion" typo in msgid strings

- src/core/crypto/AES.cpp
- src/core/crypto/BlowFish.cpp
- src/core/crypto/TwoFish.cpp
- src/core/crypto/hmac.h
- src/core/crypto/sha1.cpp
- src/core/crypto/sha256.cpp
- src/core/crypto/sha256.h
These files are from one lib, so there is no need to resolve them using "additional include paths", also this simplifies include paths for os lib.
> Use relative path for core headers in core/crypto

- Xcode/pwsafe-xcode6.xcodeproj/project.pbxproj
- src/os/file.h
- src/ui/wxWidgets/MenuFileHandlers.cpp
* Add new & moves files to appropriate groups/targets
* Fix Include path for 'os'
* Include headers required for symbols used in sources
Only built one scheme on Xcode 8.2.1
> Fix Xcode build

- Xcode/pwsafe-xcode6.xcodeproj/project.pbxproj
It builds and works fine without any changes. No reason to exclude
it from build by default.
> Enable "qrcode password display" feautre on OSX by default

- src/ui/Windows/CompareResultsDlg.cpp
Detected by compiler (for some reason it decided that `GetPassword()` marked as `nodiscard`)
> Fixed typo in assignment

- src/ui/wxWidgets/PasswordSafeFrame.cpp
Starting from 06403ca63d93e7300cd2862cfe055af15ab5a186 is was not possible to add new groups or entires from the treeview in case of an empty database. The reason is that in this case there is neither root nor group selection so menu items will be dimmed. Fixing.
> Fixing adding new groups and entires from treeview

- README.LINUX.md
Beside installation through the .deb package it's also possible to easily install password safe in Debian through apt.
> Add note in readme for Debian installation

- src/ui/wxWidgets/QRCodeDlg.cpp
Compilation with wxwidgets with no precomp headers is broken since commit 5b670035ed722b1351500610c1029ba8dd17179b as wx/wx.h is not included in this case.
Adding missing header.
> Adding missing wxwidget header

- src/ui/wxWidgets/I18N/Makefile
wxTRANSLATE() is used for translation in case of static array initialization. However, it is not passed to xgettext (only _() ) so those strings will not appear in .pot/.po files. Adding it to xgettext.
> Passing wxTRANSLATE as well to xgettext

- src/ui/wxWidgets/Clipboard.cpp
- src/ui/wxWidgets/wxUtilities.h
Quick fix to support clipboard paste in FF with Wayland backend (should fix sf-bug 1500). 
Almost the same trick as for DnD support, but with other mime-type.
> [wx] Adjust clipboard formats to support Clipboard copy into Firefox with Wayland backend

- .gitpod.Dockerfile
- Misc/setup-deb-dev-env.bash
Concluded that gitpod using `sudo apt-get` results in a permission issue (https://github.com/gitpod-io/gitpod/issues/1565). This is a workaround for this issue.
File setup-deb-dev-env
- This file has extension `.sh`, but is using a shebang `#!/bin/bash` for bash and in previous commit was calling `sh` to call this script which might break on some environments i.e environments without shebang support compiled in kernel and systems without dynamic linking (not necesary linked to gitpod, but good practice)
- Was using `apt-get` without `-y` which would cause an infinite loop in gitpod's docker environment that doesn't have set `DEBIAN_FRONTEND=noninteractive` to workaround https://github.com/gitpod-io/gitpod/issues/1171
Shellcheck (https://github.com/koalaman/shellcheck) has been recommended …
> Gitpod: Workaround for https://github.com/gitpod-io/gitpod/issues/1565

- .github/workflows/main.yml
- Xcode/pwsafe-xcode6.xcodeproj/project.pbxproj
This PR would probably generate a build using Github actions. There would be an Artifact link under the Checks tab, which would let you download a dmg. Users need to drag pwsafe.app from the dmg to their Applications folder.
Once merged, every subsequent PR would probably generate such a build.
However, this is a very minimal effort. The user would first need to install wxWidgets on his Mac by running "brew install wxWidgets".
This PR has another change that has been lying around in my fork: 883f38a: Enable QR code feature on Mac. It doesn't add any new dependencies. No reason to turn off the feature.
> Generate macOS builds using Github actions

- .github/workflows/main.yml
- README.LINUX.DEVELOPERS.md
This PR will enable bundling the required wxWidgets dylibs (shared objects) with pwsafe, along with their dependencies. The resulting dmg is entirely self-contained: no need to run 'brew install wxwidgets' anymore.
Right now, the full list of bundled libraries consists of
libjpeg.9.dylib				libwx_baseu_net-3.0.0.5.0.dylib		libwx_osx_cocoau_html-3.0.0.5.0.dylib
libpng16.16.dylib			libwx_baseu_xml-3.0.0.5.0.dylib		libwx_osx_cocoau_qa-3.0.0.5.0.dylib
libtiff.5.dylib				libwx_osx_cocoau_adv-3.0.0.5.0.dylib	libwx_osx_cocoau_xrc-3.0.0.5.0.dylib
libwx_baseu-3.0.0.5.0.dylib		libwx_osx_cocoau_core-3.0.0.5.0.dylib
These are all copied alongside the pwsafe binary. They are not installed to any system directory like /usr/lib, or even /usr/local or /opt. They stay inside the pwsafe bundle directory. …
> Bundle dependent libraries with pwsafe

- .github/workflows/main.yml
- Xcode/pwsafe-xcode6.xcodeproj/project.pbxproj
Removed all dependencies on homebrew. Now we build wxWidgets ourselves and link to it statically, so there are no non-Apple runtime dependencies.
Builds produced by the new workflow should run on macOS 10.9+, though I've only tested on 10.11 and 10.15. I don't have the other versions of macOS but I'm reasonably certain that it'd work.
wxWidgets takes about 30 minutes to build, so we cache the build outputs. This PR should build wxWidgets and cache it so the subsequent builds would be faster (nearly 4 minutes).
Sometimes, the build cache is not used:
1. If the PR is from a branch A to branch B, but A didn't branch off B
2. If the cumulative build cache size exceeds 5 GB. Each build is ~ 48mb
3. If you change the wxWidgets version, macOS version being built for, or the Xcode version
4. The …
> Build & cache wxWidgets locally (#3)

- install/deb/postinst
- install/deb/prerm
Some distributions (debian, arch, maybe others) do not always create
the system-level /usr{,/local}/share/destop-directories paths which are
required for xdg-desktop-menu and similar programs to work correctly.
In addition, the prerm script uses the -e bash option (exit on non-zero
status).  However, the postinst script does not.
This can lead to the situation where the deb package can be installed,
but cannot be uninstalled. (upgrading still works)
This commit adds checks to the postinst and prerm scripts to only run the
xdg programs if at least one of the required directories exists.
This commit also adds the -e bash option to the postinst script, for
consistency.
> Only run xdg-* functions in deb postint, prerm if the requried dirs exist

- src/core/PWSprefs.cpp
- src/ui/wxWidgets/AddEditPropSheetDlg.cpp
- src/ui/wxWidgets/EditShortcutDlg.cpp
- src/ui/wxWidgets/PasswordSafeFrame.cpp
The last change on master had introduced implicit conversion of parameter, which lead to warnings. This is fixed with the change.
In addition the filter, e.g. not saved entries, had not been updated at the gui when undo or redo is done while the filter is active. This problem is fixed as well.
> Remove warning about implicit conversion and fix problem with filter view

- src/core/core.h
- src/core/core.rc2
- src/ui/Windows/I18N/pos/pwsafe_cz.po
- src/ui/Windows/I18N/pos/pwsafe_de.po
- src/ui/Windows/I18N/pos/pwsafe_dk.po
- src/ui/Windows/I18N/pos/pwsafe_es.po
- src/ui/Windows/I18N/pos/pwsafe_fr.po
- src/ui/Windows/I18N/pos/pwsafe_hu.po
- src/ui/Windows/I18N/pos/pwsafe_it.po
- src/ui/Windows/I18N/pos/pwsafe_kr.po
- src/ui/Windows/I18N/pos/pwsafe_nl.po
- src/ui/Windows/I18N/pos/pwsafe_pl.po
- src/ui/Windows/I18N/pos/pwsafe_pt_br.po
- src/ui/Windows/I18N/pos/pwsafe_ru.po
- src/ui/Windows/I18N/pos/pwsafe_sl.po
- src/ui/Windows/I18N/pos/pwsafe_sv.po
- src/ui/Windows/I18N/pos/pwsafe_tr.po
- src/ui/Windows/I18N/pos/pwsafe_zh.po
- src/ui/wxWidgets/I18N/pos/pwsafe_da.po
- src/ui/wxWidgets/I18N/pos/pwsafe_de.po
- src/ui/wxWidgets/I18N/pos/pwsafe_es.po
- src/ui/wxWidgets/I18N/pos/pwsafe_fr.po
- src/ui/wxWidgets/I18N/pos/pwsafe_hu.po
- src/ui/wxWidgets/I18N/pos/pwsafe_it.po
- src/ui/wxWidgets/I18N/pos/pwsafe_ko.po
- src/ui/wxWidgets/I18N/pos/pwsafe_nl.po
- src/ui/wxWidgets/I18N/pos/pwsafe_pl.po
- src/ui/wxWidgets/I18N/pos/pwsafe_ru.po
- src/ui/wxWidgets/I18N/pos/pwsafe_sv.po
- src/ui/wxWidgets/I18N/pos/pwsafe_zh.po
Sorry, I did not noticed building core_st.cpp derived from core.rc2. Now it is corrected and building a Report on find will not crash in wxWidgets environment.
> Add missing string resources and update text to long string

- install/desktop/pwsafe.desktop
The app icon is missing from the dash, the top panel and the window switcher in GNOME Shell under Wayland.
This is solved by adding "StartupWMClass=pwsafe" to passwordsafe.desktop to enable GNOME Shell to map the application to its icon under Wayland.
Closes https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=988062
> Add "StartupWMClass=pwsafe" to passwordsafe.desktop

- Misc/osx-build-wx
- Xcode/generate-configs
- src/core/PWSprefs.cpp
- src/ui/wxWidgets/ComparisonGridTable.h
- src/ui/wxWidgets/DragBarCtrl.cpp
- src/ui/wxWidgets/PasswordSafeFrame.cpp
- Avoid assert with no delimiter setting in display options
- Set/unset text beneath icons in menu bar according to display options
- Enable compilation/linking on MacOS using Xcode as build environment
Hint: wxWidgets 3.0.5 is not able to run with the actual development on MacOS, while 3.1.4 is able, but background of tree view is grey and not white as the icons background is - the last one is fixed with 3.1.5 development branch of wxWidgets.
> Hotfix to avoid assert with no delimiter configured in menu bar, enable compilation for MacOS using Xcode

- install/macosx/Makefile
Update Makefile to copy missing languages into MaxOS dmg file.
> Add missing copy for languages in Makefile

- Misc/setup-linux-dev-env.sh
It's based on Ubuntu and follows the same versioning scheme, so should
be using the same dependency versions.
Building works fine otherwise.
> Add support for installing dependencies on Pop! OS

- src/ui/wxWidgets/PasswordSafeSearch.cpp
- src/ui/wxWidgets/SelectionCriteria.cpp
During translation updates for German at this line (separate PR), the following strange English translation came up. Maybe in the past it only stated "were:" but now the operation is also given. I would replace the "were" with _from_ <operation> or with _with_.
Current report looks like this where the text is used
```
...
All entries were Find with corresponding entries from "/path/test.psafe3"
All fields in matching entries were Find
...
```
> [wx] Update to English text in SelectionCriteria

- src/ui/wxWidgets/I18N/pos/pwsafe_de.po
Similar to the English version, changed the German part accordingly.
See https://github.com/pwsafe/pwsafe/pull/819.
> [wx] Improve German translation for report strings

- CMakeLists.txt
This PR makes two changes to how the CPack variable `CPACK_PACKAGE_FILE_NAME` is defined - neither change should affect the definition for `dpkg`-based systems.
The first change simply removes the architecture tag from the file name when `dpkg` is not present (rather than adding "i386" regardless of how the package was actually built).
The second change fixes an unsanitized use of the `NAME` variable from os-release which is permitted to contain whitespace.  This led CPack to interpret the filename as a list on Fedora 35 (value is "Fedora Linux") and error out during RPM generation.  This corrects that behavior by using `ID` from os-release which is guaranteed by spec (`man 5 os-release`) to contain no whitespace.
> [cpack] Update definition of CPACK_PACKAGE_FILE_NAME

- CMakeLists.txt
Mostly cosmetic but there is currently double slashes in XML install path on Linux.
For example an excerpt of a Nix build:
```
-- Installing: /nix/store/f2j49p6l23hds07irqzpn7d39rgp04i9-pwsafe-1.14.0/share/passwordsafe//xml
-- Installing: /nix/store/f2j49p6l23hds07irqzpn7d39rgp04i9-pwsafe-1.14.0/share/passwordsafe//xml/pwsafe.xsl
-- Installing: /nix/store/f2j49p6l23hds07irqzpn7d39rgp04i9-pwsafe-1.14.0/share/passwordsafe//xml/pwsafe_filter.xsd
-- Installing: /nix/store/f2j49p6l23hds07irqzpn7d39rgp04i9-pwsafe-1.14.0/share/passwordsafe//xml/pwsafe.xsd
```
With the proposed change:
```
-- Installing: /nix/store/privbg5myn9xzgaff5pwvcr5bl2m71pb-pwsafe-1.14.0/share/passwordsafe/xml
-- Installing: /nix/store/privbg5myn9xzgaff5pwvcr5bl2m71pb-pwsafe-1.14.0/share/passwordsafe/xml/pwsafe.xsl
-- …
```
> Fix xml install path on Unix platforms

- src/ui/wxWidgets/SafeCombinationEntryDlg.cpp
This is an attempt to fix the reported issue [1548](https://sourceforge.net/p/passwordsafe/bugs/1548/) on SourceForge.
It's untested because I don't have a Yubikey.
> [wx] Fix file path name for Yubi

- src/core/ItemData.cpp
```
ItemData.cpp:1942:23: error: variable-sized object may not be initialized
unsigned char buf[len] = {0};
```
> Fix build on big-endian architectures

- src/ui/Windows/MainFile.cpp
Since commit 103134a6e, the maximized window is saved in the prefs
as an empty rect (0, 0, 0, 0). So do the maximized check first.
Previously, the visibility check (RectInRegion) would always win and
ignore the empty rect thus not restoring the maximized state.
The fix is not complete. The following situation is still not right:
1. Place Window in the middle of the screen.
Normally, if you close the program and open it again, the window
is shown in the same place.
2. Click Maximize button and close the program.
Windows position is saved as (0, 0, 0, 0).
3. Open the program again. Window is shown as Maximized.
This didn't work. This commit fixes it.
4. Click Restore button.
Window is restored to the top-left corner with some default size.
Expectation: Windows is restored to its previous …
> [SF1545] Restore maximized status of the window on program start

- src/os/unix/pws_time.h
Fixes build failure with GCC 12:
```
/var/tmp/portage/app-admin/passwordsafe-1.15.0/work/pwsafe-1.15.0/src/os/unix/pws_time.cpp: In function ‘int localtime64_r(const __time64_t*, tm*)’:
/var/tmp/portage/app-admin/passwordsafe-1.15.0/work/pwsafe-1.15.0/src/os/unix/pws_time.cpp:30:10: error: ‘localtime_r’ was not declared in this scope; did you mean ‘localtime64_r’?
30 |   return localtime_r(tp, result) != nullptr;
|          ^~~~~~~~~~~
|          localtime64_r
/var/tmp/portage/app-admin/passwordsafe-1.15.0/work/pwsafe-1.15.0/src/os/unix/pws_time.cpp: In function ‘int pws_os::asctime(TCHAR*, size_t, const tm*)’:
/var/tmp/portage/app-admin/passwordsafe-1.15.0/work/pwsafe-1.15.0/src/os/unix/pws_time.cpp:36:3: error: ‘asctime_r’ was not declared in this scope
36 |   asctime_r(t, cbuf);
| …
```
> Fix build with GCC 12 (missing <time.h> include)

- src/ui/wxWidgets/PasswordSafeFrame.cpp
(Can't test this directly, but doesn't seem to break Debian/Fedora/Ubuntu.)
See #878 for details.
> BR878: macOS UX fix

- src/ui/wxWidgets/AddEditPropSheetDlg.cpp
Allow copy of field content in View Entry by Ctrl-C/Command-C.. The Close buttons standard-binding is to this key. So using Abort instead of Close will lead to demanded functionality,
> Allow copy of field content in View Entry by Ctrl-C/Command-C.

- .github/workflows/codeql-analysis.yml
- .github/workflows/macos-latest.yml
- .github/workflows/ubuntu-latest.yml
This PR adds minimum token permissions for the GITHUB_TOKEN in GitHub Actions workflows using [secure-workflows](https://github.com/step-security/secure-workflows).
The GitHub Actions workflow has a GITHUB_TOKEN with write access to multiple scopes. Here is an example of the permissions in one of the workflow runs:
https://github.com/pwsafe/pwsafe/actions/runs/3168160062/jobs/5159162157#step:1:19
After this change, the scopes will be reduced to the minimum needed for the following workflows:
- codeql-analysis.yml
- macos-latest.yml
- ubuntu-latest.yml
- This is a security best practice, so if the GITHUB_TOKEN is compromised due to a vulnerability or compromised Action, the damage will be reduced.
- [GitHub recommends](https://docs.github.com/en/actions/security-guides/automatic-token-authe …
> ci: add minimum GitHub token permissions for workflows

- src/ui/wxWidgets/TreeCtrl.cpp
Edit tree list view group name by direct editing.
> Correct issue #888. Allow direct group name editing in tree view

- src/Tools/Windows/I18N/ResText/UnicodeUtils.cpp
No x86/x64 intrinsics are used and it breaks arm64 builds.
> Remove an x86/x64 include from UnicodeUtils.cpp.

- src/core/PWCharPool.cpp
We don't need `std::random_device` and `std::mt19937` when we already have `pwsrng` two lines above.
> Pick the "leet" substitutions with PWSrand.

- src/ui/Windows/I18N/CMakeLists.txt
Build the dependency list instead of having a separate copy.
The Visual Studio generator doesn't care that the "${DLL_DIR}/pwsafePT.dll" target is missing ("pwsafePT_BR.dll" is being generated).  Ninja complains about the missing target.
> A missing "dlls" target dependency breaks Ninja.

- .github/workflows/macos-latest.yml
I'd like to suggest we update to wxWidgets 3.2.2.1 (the current version).  3.2.1 has a Mac specific bug that does strange things to the font rendering.  For example, in the tree view, as I click around, the list font seems to toggle between normal and a highlight or bold look.  It might depend on font size and whether or not you have a HiDPI monitor (I don't.). I've been using 3.2.2.1 since its release and I haven't noticed any new problems.
This commit only changes the macOS build and sets FORCE_REBUILD_WX=6.
> [macOs] Update to wxWidgets 3.2.2.1

- CMakeSettings.json
- src/core/CoreImpExp.cpp
- src/core/PwsPlatform.h
use CMake template msvc_arm64_x64
also "fix" one issue in struct TextRecordWriter, const unsigned char *utf8 was considered uninitialized. Initialize as nullptr.
> add targets for Windows ARM64

- src/ui/Windows/SystemTray.cpp
Observe WM_LBUTTONUP instead of WM_LBUTTONDBLCLK on pwsafe system tray icon to activate pwsafe and trigger login.
https://github.com/pwsafe/pwsafe/issues/959
IMPORTANT: This change will modify the Windows UX from requiring a double-click to only needing a single-click upon the Windows system tray icon in order to activate the pwsafe password entry modal dialog box. All Windows system tray icons/apps observed on a handful of systems use only a single-click to activate app windows, and a single-click is both faster and more ergonomically friendly. If most Windows system tray icons use a single click, this change should also allow pwsafe to align its system tray usage with Windows product testing around system tray icons (i.e., it seems likely there is more user coverage for single-click …
> Single-click to activate password entry.

- src/core/CheckVersion.cpp
- src/core/SysInfo.cpp
- src/core/SysInfo.h
- src/ui/wxWidgets/AboutDlg.cpp
- src/ui/wxWidgets/PasswordSafeFrame.cpp
Clicking the link to check for a newer version from the About dialog causes the app to abort when closing the database.  (See attached screenshot.)
The first commit fixes that problem by delaying closing the About dialog until after the process to close the database.  I don't currently have a Linux environment set-up to test this patch.  For that matter, I'm not really sure if the problem even happens on Linux, there are some differences in that part of wxWidgets.  I hope someone can test the Linux build before merging this PR.  If there is a problem, or some other reason for discomfort, these changes should be easy to ifdef.
Secondary problem:  Once it stopped crashing, I discovered it was checking the PC version number instead of the combined Mac/Linux WX version.  The second commit …
> macOS: Check for new version crashes the app

- src/ui/wxWidgets/ExternalKeyboardButton.cpp
On macOS, the external keyboard button on the open dialog doesn't do anything.  I'm not sure this is good but I can't figure out how to open the virtual keyboard, so this patch will open the System Settings app to the right page and prompt the user to enable it.  Any thoughts?
> macOS: Let the External Keyboard Button.cpp do something

- src/ui/wxWidgets/PasswordSafeFrame.cpp
The clear clipboard on minimize option does not work unless the lock DB on minimize option is set.  This change will clear  the clipboard in either case.  This would affect both Mac and Linux, but I've only tested on Mac.
> Fix clear clipboard on minimize option

- src/os/mac/debug.cpp
- src/ui/cli/main.cpp
- Add a call to setrlimit() to prevent core files in a release build (macOS only, already in Unix versions) 
(In normal execution, the soft limit defaults to 0, but I was able to get around it.)
- Add a call to pws_os::DisableDumpAttach() to pwsafe-cli so it too will have core files and debugging restricted. (Potentially affects all builds.)
This was tested on macOS Ventura 13.5 with Xcode 14.3.1 and wxWidgets 3.2.2.1.   pwsafe-cli should be tested on Linux as well.
> wx: Prevent core files and debugging in release builds

- src/ui/wxWidgets/GuiInfo.cpp
Ensure the tree view information is preserved on lock so it can be restored when the file is unlocked.
See discussion in #1001 and #954.  The crux of the problem is redundant calls to GuiInfo::SaveTreeViewInfo, the last one happening after the info has been cleared.  I noted that GuiInfo::SaveGridViewInfo already had a check for an empty grid, so I added a similar check to GuiInfo::SaveTreeViewInfo.  Note that there are also redundant calls to restore the grid/tree views. 
This was tested on macOS Ventura 13.5 with Xcode 14.3.1 and wxWidgets 3.2.2.1.   It needs re-testing on Linux.
> Mac and Linux: Save/Restore tree view on lock/unlock

- src/ui/wxWidgets/PWSafeApp.cpp
- src/ui/wxWidgets/PWSafeApp.h
- (Mac only) When the system tray is enabled, a locked window cannot be restored by clicking on the dock icon.  Allowing this makes the behavior more Mac like.
- Fixed a few override warnings in PWSafeApp.h, since I was there anyway.
This was tested on macOS Ventura 13.5 with Xcode 14.3.1 and wxWidgets 3.2.2.1. 
> Mac: Unlock with dock icon

- src/ui/wxWidgets/DbSelectionPanel.cpp
- src/ui/wxWidgets/ExportTextWarningDlg.cpp
- src/ui/wxWidgets/PWSafeApp.cpp
- src/ui/wxWidgets/SafeCombinationChangeDlg.cpp
- src/ui/wxWidgets/SafeCombinationEntryDlg.cpp
- src/ui/wxWidgets/SafeCombinationPromptDlg.cpp
- src/ui/wxWidgets/SafeCombinationSetupDlg.cpp
- src/ui/wxWidgets/YubiCfgDlg.cpp
- src/ui/wxWidgets/YubiMixin.cpp
- src/ui/wxWidgets/YubiMixin.h
This is an untested attempt to make the Yubi Key polling interval configurable via command line argument "-y".
This PR is related to the suggestion in #882 and has not been tested due to the lack of a Yubi Key.
1. Should the command line argument be "-y, --yubi_polling_interval" or "-p, --polling"?
2. Should an environment variable be used rather than a command line option?
> Make YubiKey polling interval configurable

- src/ui/wxWidgets/PWSafeApp.cpp
Changes based on review [comment](https://github.com/pwsafe/pwsafe/pull/1024#issuecomment-1708932461) in #1024.
> [wx] Remove command line short option for YubiKey polling timer configuration

- src/ui/Windows/StateBitmapManager.cpp
- src/ui/Windows/StateBitmapManager.h
GDI objects were being deleted, but CBitmap instances remained. Given current usage, leak is minor at ~96 bytes each time a password dialog is dismissed.
> Fix minor CStateBitmapManager resource leak.

- src/ui/wxWidgets/PasswordPolicyDlg.cpp
This is a follow-up to #1043, that also relates to minimum numbers of characters requires for different character classes. All descriptions of #1043 are applicable here by extension.
> Fix: minimum char class lengths not updated from the policy in the generator (wx)

- README.LINUX.DEVELOPERS.md
Add info on running the core test suite.
> Add 'make test' to  README.LINUX.DEVELOPERS.md

- src/ui/wxWidgets/SystemTray.cpp
This is in reference to Issue #1009 
On macOS, the systray unlock safe menu option opens an empty window frame.  I couldn't find a way to suppress the empty window frame, so the workaround is to go ahead and fully restore the UI.
> macOS: Restore window when safe is unlocked

- src/test/TestCommon.h
Fatal error on Fedora 38:
In file included from /home/pwsafe/pwsafe/src/test/HMAC_SHA1Test.cpp:25: /home/pwsafe/pwsafe/src/test/TestCommon.h:19:33: error: 'uint8_t' was not declared in this scope
19 | using byte_vector = std::vector<uint8_t>;
|                                 ^~~~~~~
/home/pwsafe/pwsafe/src/test/TestCommon.h:17:1: note: 'uint8_t' is defined in header '<cstdint>'; did you forget to '#include <cstdint>'?
16 | #include <cstring>
+++ |+#include <cstdint>
17 | #include <vector>
> Compile error in coretest (needed to include cstdint)

- Xcode/pwsafe-xcode6.xcodeproj/project.pbxproj
- src/core/CoreImpExp.cpp
- src/core/PWCharPool.cpp
- src/core/PWSFilters.cpp
- src/core/PWScore.cpp
- src/core/PWSfile.h
- src/core/PWSfileV1V2.h
- src/core/PWSfileV4.cpp
- src/core/coredefs.h
- src/core/pugixml/pugixml.cpp
- src/os/mac/file.cpp
- src/os/unix/PWYubi.cpp
- src/ui/wxWidgets/ManagePasswordPoliciesDlg.h
- src/ui/wxWidgets/PWFiltersBoolDlg.h
- src/ui/wxWidgets/PWFiltersDCADlg.h
- src/ui/wxWidgets/PWFiltersDateDlg.h
- src/ui/wxWidgets/PWFiltersIntegerDlg.h
- src/ui/wxWidgets/PWFiltersMediaDlg.cpp
- src/ui/wxWidgets/PWFiltersMediaDlg.h
- src/ui/wxWidgets/PWFiltersPasswordDlg.h
- src/ui/wxWidgets/PWFiltersStatusDlg.h
- src/ui/wxWidgets/PWFiltersStringDlg.h
- src/ui/wxWidgets/PWFiltersTypeDlg.h
- src/ui/wxWidgets/PasswordSafeFrame.cpp
- src/ui/wxWidgets/SetDatabaseIdDlg.cpp
- src/ui/wxWidgets/SetDatabaseIdDlg.h
After updating the Mac Build to C++17, I decided to make a pass over the 80+ warnings I get from a full build.  Most were simple language related issues.  Many apply to Linux and Windows as well.  With the warning options as set in the project file (-Wall -Wextra on os and core, default elsewhere), it now compiles clean on Xcode 14.2 and 15.1, except for one warning in a WX 3.2.2.1 header. (it's fixed in WX 3.2.4.)
With respect to the "Suppress long to int conversion warnings" commit: Three crypto files generate ~30 warnings, most within macro expansions.  Since I don't have the resources to test all the versions I decided to leave them as-is and just applied "-Wno-shorten-64-to-32" to those three specific files in the Xcode project file.
> MacOS: Compiler warning clean-up

- src/os/debug.h
- src/ui/Windows/AddEdit_Basic.cpp
- src/ui/Windows/AddEdit_Basic.h
- src/ui/Windows/DboxMain.h
- src/ui/Windows/DisplayAuthCodeDlg.cpp
- src/ui/Windows/MainEdit.cpp
- src/ui/Windows/PWSclipboard.cpp
- src/ui/Windows/PWSclipboard.h
If a user pastes a TOTP code from the clipboard at the same time as pwsafe attempts to copy a TOTP code to the clipboard, pwsafe may encounter clipboard API errors due to the clipboard being busy. Retry if apparent transient clipboard availability states are detected.
> Retry copying TOTP to clipboard if clipboard busy.

- Xcode/pwsafe-xcode6.xcodeproj/project.pbxproj
- src/ui/wxWidgets/AboutDlg.cpp
- src/ui/wxWidgets/version.in
This adds the wxWidgets version number to the About dialog:
One side effect on macOS is the string "(wxWidgets)" is removed from the app name in the main menu (see before and after screenshots) , but I think it looks better this way :-)
The file version.in has a separate "#ifdef linux" branch, but it doesn't seem to be used i.e. this change also works on Linux.  If it's obsolete I can remove it.
> wx: Add wxWidgets version number to the About dlg

- src/ui/wxWidgets/DbSelectionPanel.cpp
- src/ui/wxWidgets/ExportTextWarningDlg.cpp
- src/ui/wxWidgets/PasswordSafeFrame.cpp
- src/ui/wxWidgets/SafeCombinationChangeDlg.cpp
- src/ui/wxWidgets/SafeCombinationEntryDlg.cpp
- src/ui/wxWidgets/SafeCombinationPromptDlg.cpp
- src/ui/wxWidgets/SafeCombinationSetupDlg.cpp
Unifying the terminology of Password Safe on Windows with Password Safe on non-Windows.
Changing "safe combination" with "master password" in all of *.cpp files.
> Change safe combination to master password in *.cpp files

- src/ui/Windows/res/PasswordSafe3.rc2
- src/ui/wxWidgets/DbSelectionPanel.cpp
- src/ui/wxWidgets/SafeCombinationEntryDlg.cpp
- src/ui/wxWidgets/SafeCombinationPromptDlg.cpp
If Master Password is incorrectly typed in, bellow dialog is displayed, which message is little bit confusing, What is "passkey"?, and options are too crowded.
This pull request changes dialog to:
> If incorrect master password entered, replace display more friendly message

- src/ui/Windows/PasswordSafe.rc
- src/ui/wxWidgets/OptionsPropertySheetDlg.cpp
- src/ui/wxWidgets/pwsafe.pjd
In menu Manage | Options | System change one word "PassworSafe" to two words "Password Safe".
This is just simple fix, to make product branding more recognizable.
> Change one word PasswordSafe to two words Password Safe in Manage | Options | System

- src/ui/wxWidgets/DeleteConfirmationDlg.cpp
Attempt to fix [issue 1020](https://github.com/pwsafe/pwsafe/issues/1020)
---
1. **DONE:** This commit is for non-Windows only.
---
2. **TODO:** Now searching for Windows strings and I get:
> src/ui/Windows/res/PasswordSafe3.rc2:  IDS_DELGRP              "Are you sure you want to delete the selected group?"
> src/ui/Windows/res/PasswordSafe3.rc2:  IDS_DELENT              "Are you sure you want to delete the selected entry?"
@ronys, can you confirm I should change following two strings in the code? I don't have Windows to build Password Safe Windows build.
---
3. **TODO:** @rony, it would be nice this questions have a "exclamation point" icon on the left side. Any tip how to add it?
> Rename Yes_No buttons to Delete_Cancel in Delete Group and Delete Entry on non-Windows

- src/ui/Windows/res/PasswordSafe3.rc2
- src/ui/wxWidgets/DbSelectionPanel.cpp
- src/ui/wxWidgets/SafeCombinationEntryDlg.cpp
- src/ui/wxWidgets/SafeCombinationPromptDlg.cpp
I made some additional improvements to "incorrect master password" dialog on top of [PR 1114](https://github.com/pwsafe/pwsafe/pull/1114) that was already merged into master.
Now I see that design changes in PR 1114 was not the best choice, after using program in day-to-day activity. Now I see how distracting "explanation mark" icon is and how wide is actually dialog and so trying for eyes to move so long from end of first line to second line.
- Text is the same.
- Removed icon
- Added line brake to make dialog shorter
Comparisons:
> Dialog with wrong master password. Remove dialog icon and make dialog less wide

- src/core/core.rc2
- src/ui/wxWidgets/SafeCombinationChangeDlg.cpp
- src/ui/wxWidgets/SafeCombinationSetupDlg.cpp
Attempt to fix issue https://github.com/pwsafe/pwsafe/issues/1120
Fixes for two dialogs (that have exactly the same appearing):
- "weak password" dialog if at "change master password" dialog weak password is typed in
- "weak password" dialog if at "create new database" dialog weak password is typed in
Fixes:
1. Exact problem in title instead of old "Error".
2. Replace fatal error icon with explanation point (because fatal icon should be when something is over, can't be continued). By the way on picture bellow on left site is flatpak version that does not uses icons.
3. Nitpick: add full stop and the end of error message.
4. Changed button labels from Yes_No to "action" and Cancel.
5. Set Cancel button as default button (this way already done at new database dialog, but was missing at …
> Make Weak master password dialog more pretty.

- src/ui/wxWidgets/MenuFileHandlers.cpp
Attempt to fix https://github.com/pwsafe/pwsafe/issues/1122
How to test:
1. Open password database and make sure Manage | Options | Backup tab | "Save database immediately after any change" is unchecked.
2. Delete some entry or group and confirm delete action. So change is made that is currently not saved.
3. Click on "New" or "Close" button from toolbar and dialog appears that we have unsaved changes (this PR).
Above image:
- top and bottom left Password Save 1.18.2 flatpak version
- top and bottom right changes from this PR
- first row what happen if in step 3: New button is clicked
- second row what happens if in step 3: Close button is clicked
> Unsaved database close down or new database opened

- src/ui/wxWidgets/DeleteConfirmationDlg.cpp
- src/ui/wxWidgets/DeleteConfirmationDlg.h
- src/ui/wxWidgets/MenuEditHandlers.cpp
- src/ui/wxWidgets/PasswordSafeFrame.h
This is for issue #1128 .  It converts the unused num_chidren into an isGroup bool.
> Display the correct "Are you sure" message when deleting an empty group

- src/ui/wxWidgets/TreeCtrl.cpp
How to test:
1. Type in group name.
2. On the same level type in the name with the same name and error appears. PR changes the wording of error dialog.
Changes in this PR:
1. Change "Double group name" title with "Duplicate group name" (I have also changed this title on two other errors).
2. Current text: "Same group name exists". This actually does not tell what is wrong, because group names on different levels are perfectly fine. Problem are sibling groups. I changed text to: "Group names on the same level must be unique."
> Friendlier labers for duplicate group names

- src/ui/wxWidgets/AboutDlg.cpp
In yesterday PR https://github.com/pwsafe/pwsafe/pull/1150 that was already merged master, now I see I have temporally empty the variable, so the only text in it was "" and then forgot to delete and simplify the code.
In this PR it is just a little cleanup of code.
From end-user point of view the Help About dialog looks the same before and after this PR.
> Simplify code at Help About

- src/ui/wxWidgets/PasswordSafeFrame.cpp
In program's title bar adds space. Current "PasswordSafe". This PR "Password Safe"
> Title bar PasswordSafe to Password Safe

- src/ui/Windows/PasswordSafe.rc
- src/ui/wxWidgets/SafeCombinationPromptDlg.cpp
Unify wording between dialogs:
- remove "Please" word
- explicitly tell user the action that will follow e.g. unlock database
> Remove word Please from closed database and reopened dialog

- src/ui/wxWidgets/AddEditPropSheetDlg.cpp
This is for Issue #1158.  That always kind of bugged me too.  
Note that this simple change will *always* default to the Title field.  I can imagine some scenarios where that might not be preferred, so I'm open to discussion and suggestions.
When creating the AddEditPropSheetDlg dialog, the default keyboard focus goes to the Group field.  This patch changes the default to the Title field.
> Set default focus to the Title box

- src/ui/Windows/res/PasswordSafe2.rc2
- src/ui/wxWidgets/PasswordSafeFrame.cpp
Word "Safe" is confusing and we are replacing it to "Password Database".
- Current: File | Clear Recent **Safe** List
- This PR: File | Clear Recent **Password Database** List
> Rename Safe List to Password Database in File | Clear Recent Safe List

- src/ui/Windows/res/PasswordSafe3.rc2
- src/ui/wxWidgets/MenuFileHandlers.cpp
- src/ui/wxWidgets/SafeCombinationEntryDlg.cpp
Compare dialog title in Text Editor vs Password Safe.
Simplify wording from:
- current: Please Choose a Database to Open
- this PR: Open Password Database
> Simplify title of Open dialog

- src/ui/Windows/res/PasswordSafe3.rc2
On Windows only Add Entry dialog and move mouse to the "i" icon. In second case the only "Confirm" is used instead of full name "Confirm Password".
> Button name is Confirm Password

- src/ui/wxWidgets/PropertiesDlg.cpp
Attempt to fix [1173](https://github.com/pwsafe/pwsafe/issues/1173).
By the way, this is fix for Linux build. I have no idea how to fix this on Windows. Any hint? @ronys or can you change it please?
> Change OK button to Close in File Properties

- src/ui/wxWidgets/CreateShortcutDlg.cpp
Right mouse click on entry and from menu Edit | Create Shortcut.
Remove "Please" word to simplify.
> Remove Please word from Create Shortcut dialog

- src/ui/wxWidgets/MenuManageHandlers.cpp
Manage | Restore from Backup. Simplify title bar.
> Change title bar of Restore Database dialog

- src/ui/wxWidgets/AddEditPropSheetDlg.cpp
- src/ui/wxWidgets/AddEditPropSheetDlg.h
- src/ui/wxWidgets/YubiCfgDlg.cpp
- src/ui/wxWidgets/wxUtilities.cpp
- src/ui/wxWidgets/wxUtilities.h
- Directly/Dynamically changing the style flags of a password text control also improves the layout behavior of YubiCfgDlg.
- The ShowHideText code in wxUtilities was pretty much identical to that of AddEditPropSheetDlg::UpdatePasswordTextCtrl.
> [wx] Merge 'AddEditPropSheetDlg::UpdatePasswordTextCtrl' with 'ShowHideText' from wxUtilities to prevent redundant code

- src/ui/wxWidgets/YubiCfgDlg.cpp
Makes the text control for “YubiKey Serial Number” stretchable and may fix what the following comment in YubiCfgDlg::CreateControls() points out.
> With wx:3.2.2.1 this text wxTextCtrl doesn't resize, it stays one character wide. The initial string of 0s forces it.
> [wx] Minor improvement on layout of YubiCfgDlg

- src/ui/wxWidgets/TreeCtrl.cpp
- src/ui/wxWidgets/TreeCtrl.h
- Resolves #1145 
- Also seems to fix a crash when ESC cancels editing of a group name.
- Would be great if someone could also check the behavior on a Mac.
> [wx] Fix re-editing issue of group name in tree view

- .github/workflows/macos-latest.yml
Build the Yubico libraries from specific commits, since they don't use tags.  These commits are the current master/HEAD, so they correspond the build that is already in use, and they are the same as proposed for the flathub build.
> Use specific commits from the Yubico repos

- .github/workflows/macos-latest.yml
I've been using this version for local builds since its release.  It's also the version used for the flathub build.
> Update macos-latest.yml to use wx 3.2.4

- src/ui/wxWidgets/SafeCombinationSetupDlg.cpp
Attempt to fix: https://github.com/pwsafe/pwsafe/issues/1208
When new database is created change title of "Error" to actual problem.
Idea is to replace "Error" in title bar with actual problem. We have already fixed "Error" with "Weak Master Password" title when database is created with weak master password.
Few more:
1. When empty password: Empty Master Password.
2. When master password and confirmation do not match: Mismatch Master Password.
Similar issue that I have fixed in the same file:
3. Yubikey entries do not math: Mismatch entries.
> Change dialog title from Error to actual problem

- src/ui/wxWidgets/AddEditPropSheetDlg.cpp
Password Safe v1.19.2-prerelease on Ubuntu 23.10.
1. New Entry and add new entry.
2. Duplicate entry from step 1.
3. Edit Entry and name the entry with the same name as in step 1 and error appears with dialog title "Error". This PR changes "Error" title bar with real problem name "Duplicate entry".
> Change title of dialog from Error to real action name Duplicate entry

- src/ui/wxWidgets/AddEditPropSheetDlg.cpp
Password Safe v1.19.2-pre on Ubuntu 23.10.
1. Edit Entry.
2. Make sure Password and Confirm are different. Error is returned. This PR changes dialog title from "Error" to "Mismatching passwords" and adds full stop at the end of sentence.
> Change title bar from Error to Mismatching passwords

- src/ui/wxWidgets/AddEditPropSheetDlg.cpp
- src/ui/wxWidgets/PasswordPolicyDlg.cpp
1. Change Error title to real problem "Duplicate selection".
2. Remove word "Sorry", because it is unusual wording and redundant - simplification.
3. Two pairs of the same problem but order of selections are reversed. Unify the error message.
> Change dialog title, remove word Sorry and unify the same error with the same message

- Misc/setup-linux-dev-env.sh
The prerequisites are the same for both regular Fedora Linux and Fedora Asahi Remix.
Tested on Fedora Asahi Remix 40. Builds without errors, automated tests pass, and works correctly when run manually.
> Add Fedora Asahi Remix to Linux prereqs script

- src/ui/wxWidgets/SafeCombinationEntryDlg.cpp
While testing the last merges I noticed that the Yubi status text appears to the left of the help button on the entry dialog. This is probably code that was forgotten to be removed or result of the merges?!
> [wx] Remove misplaced Yubi status text control

- src/ui/wxWidgets/Clipboard.cpp
> Mark copied password as secret for Linux

- src/ui/wxWidgets/SafeCombinationChangeDlg.cpp
- src/ui/wxWidgets/YubiMixin.cpp
- src/ui/wxWidgets/YubiMixin.h
This PR refers to https://github.com/pwsafe/pwsafe/pull/1215#issuecomment-2059550069 and was fixed by updating the dialog's sizer hints so that the dialog is resized to the new required size.
By manually changing the dialog size, the bottom buttons can no longer be reduced below their required minimum size and thus retain their full size.
Another change is that the layout will only be updated once when the Yubi controls are displayed and no longer periodically with the poll rate (0.5 seconds), in the hope that it has a positive effect on performance.
It would be great if a YubiKey owner could test these changes.
> [wx] Fix layout issue when showing Yubi controls dynamically

- src/ui/wxWidgets/Clipboard.cpp
Related PR: #1287 
After checking wxWidgets and KDE source code, it looks like the data is not a null terminated string... Changing to `memcpy` to avoid copying the null terminator, which may not fit in the buffer. 
I have tested this again on Kubuntu 24.04, copy and clear clipboard are working as expected. 
@ronys Sorry that I missed this in my other PR. Please take a look at this change.
> Fix GetDataHere logic to avoid copying the null terminator

- src/core/PWSAuxParse.cpp
- src/ui/wxWidgets/MenuEditHandlers.cpp
Relates to #1105 and https://github.com/pwsafe/pwsafe/commit/f690c01c8d698052c6f28c4d23680ac1f7a4ef13, and possibly related to #1282 . 
Currently, backslash isn't typed for username (and group, title, url, email) on Windows, and is typed twice for password (and previous password) on Linux. 
Changes: 
1. Add backslash escape to group, title, username, url, and email. 
2. Update `MenuEditHandlers.cpp > PasswordSafeFrame::DoAutotype` (which is used by Linux) to better match `PWSAuxParse.cpp > PWSAuxParse::SendAutoTypeString` (which is used by Windows). 
Linux (Kubuntu 24.04): 
Windows 10 (VM):
> Fix backslash handling for autotype

- .github/workflows/macos-latest.yml
The current GitHub macOS image has gettext pre-installed, so this is to eliminate a needless brew error message.
> gettext is already installed

- docs/ReleaseNotesWX.md
- src/ui/wxWidgets/SafeCombinationChangeDlg.cpp
Resolves #1230
Corrects some behavior when using a Yubikey:
- Allows the old password to be blank
- Requires that the new and confirmation fields match
- After validating the old password/Yubikey combo, advance the focus to the New PW field
Tested on:
macOS M1Max Sonoma 14.5, Xcode 15.4, wx 3.2.4 (local debug build)
Fedora 40 ARM64, Xfce/X11, gcc 14.1.1, wx 3.2.4, GTK 3.24.42
> Fix logic issues in the Change Master Password dialog

- docs/ReleaseNotesWX.md
- src/ui/wxWidgets/SafeCombinationChangeDlg.cpp
- src/ui/wxWidgets/SafeCombinationSetupDlg.cpp
- src/ui/wxWidgets/wxUtilities.cpp
- src/ui/wxWidgets/wxUtilities.h
Resolves #1300 for Mac and Linux.  Similar changes are still needed for Windows.
- Move some duplicated code to a new function: CheckPasswordStrengthAndWarn() in wxUtilities.cpp
- Add calls to the "Set Master Password" and the "Change Master Password" dialogs; with and without a Yubikey
> [wx] Use the password strength check with a Yubikey

- src/core/PWScore.cpp
- src/core/PWScore.h
- src/ui/wxWidgets/PasswordSafeFrame.cpp
When a file is already open, and the user tries to open a different file via "File->Open..." or the Open button, the already open file is saved and closed, but its lock file is not removed.
> [wx] Clear old lock on open

- src/ui/wxWidgets/Clipboard.cpp
- src/ui/wxWidgets/wxUtilities.cpp
- src/ui/wxWidgets/wxUtilities.h
As per #1308 and #1307, copying composite objects are not working as expected on Wayland. 
I checked around the Internet, and it looks like some other projects are also having difficulties with composite objects and Wayland (example: https://github.com/flameshot-org/flameshot/issues/2848)
Adding a check for the display manager and only add the password manager hint when the display manager is X11.
> fix: check for display manager before adding password manager hint

- docs/formatV4.txt
This copies the TOTP parameters from V3.
> TOTP parameters missing from V4 format specification

- src/ui/wxWidgets/SafeCombinationEntryDlg.cpp
- src/ui/wxWidgets/SafeCombinationPromptDlg.cpp
A minor regression in PR #1335 prevents Yubikey related error messages (e.g. Timeout) from being displayed in the status field.
> [wx] Yubikey error messages not displayed

- src/ui/cli/main.cpp
With reference to #1349 , notes on how to use some fields and notes on how to specify timestamps have been added to the usage output. In addition, some examples of how to use the fields have been added. I would have liked to have added an example of how to change existing fields of an entry, but unfortunately I was unable to do so.
If further questions are asked about how to use the command line version, the list of notes and examples can be expanded to make it easier for the user to use the command line version.
> [CLI] Add examples to usage output

- src/os/mac/dir.cpp
Carbon is macOS only, both support CoreFoundation.
> Replaced Carbon include with CoreFoundation for iOS compatibility

- src/os/mac/debug.cpp
ptrace is not available on iOS. More info on that [here](https://forums.developer.apple.com/forums/thread/701621).
This commit changes nothing for macOS.
> Do not use ptrace API on iOS

- src/os/mac/media.cpp
This removes the dependency of mac/media.cpp on the wx framework. On iOS the wx framework is not available.
To determine a file's mimetype, the CoreServices framework is used, which is available on both macOS and iOS by default.
This uses the native mimetype database from macOS/iOS, as used by all programs and the OS itself.
> Use CoreServices for determining mime type

- src/core/crypto/sha1.cpp
- src/core/crypto/sha1.h
The HMAC interface assumes 64-bit support in the hash algo, so here is the update for sha1.
It is actually a simplification of the code.
And the compiler (clang) is happy (2 warnings disappeared) now that this is resolved.
> Allow 64-bit update call to SHA1::Update as required by HMAC class

- src/ui/wxWidgets/PWSafeApp.cpp
Each time the app is started and exited, the window size, as saved in the config file, shrinks by one pixel.  When subtracting co-ordinates  (e.g. bottom-top) we need to add one to get the number of pixels, inclusive.
> [WX] Converting co-ordinates to width and height needs a +1

- CMakeLists.txt
- docs/ReleaseNotesWX.md
Fixes #1372 , per Balazs's suggestion.
> [br1372][linux] Regression: man page now installs in correct location

- src/core/ItemData.h
This avoids an unnecessary time_t -> StringX -> time_t conversion roundtrip in the iOS app, I think useful to other platforms too
> Added SetTotpStartTime(time_t t) similar to other time_t fields

- src/ui/wxWidgets/AddEditPropSheetDlg.cpp
Mac only follow-on to PR #1353 
Other platforms have a drop down calendar feature on their date picker control.  wxWidgets does not use that by default on macOS, apparently because it was not available prior to macOS 10.15.4.
This PR enables the wxDP_DROPDOWN option on macOS 10.15.4 and above, otherwise we continue to use the current value (wxDP_DEFAULT) because the documentation is somewhat vague as to the behavior in other cases.  This was tested on:
macOS M1Max Sonoma 14.6.1, Xcode 15.4, wx 3.2.4 and 3.2.5
Fedora 40 ARM64 VMware,    KDE/Wayland,   gcc 14.1.1, wx 3.2.4, GTK 3.24.43
Ubuntu 24.04 ARM64 VMware, Gnome/Wayland, gcc 13.2.0, wx 3.2.4, GTK 3.24.41
wxCHECK_VERSION was added to allow it to compile with wx3.0.5, but that build was not tested.
> [macOS] Use the drop down month date picker on macOS, if supported

- src/core/UTF8Conv.cpp
- src/os/mac/utf8conv.cpp
On macOS, pws_os::wcstombs ignored the isUTF8 argument. By calling std::wcstombs the user-preferred encoding is used (as instructed by Startup). This causes e.g. incorrect calculations of stretched keys if a non-UTF8 locale is used. This PR fixes that.
Below is a simple code snippet that demonstrates the issue on macOS (unit-tests do not run on macOS, so that is why I include it here for reference). After applying this PR the test works ok.
- PWScore::CheckPasskey will try both true and false for isUTF8 (using PWS_PK_CP_ACP). This allows unlocking safes that were saved with incorrect stretched keys as pws_os::wcstombs will fallback to the old (erroneous) behavior.
- pws_os::mbstowcs needs similar fix, seems to have less impact, will add that to this PR.
- there might be compatibility …
> If caller requests UTF8 encoding then use UTF8 encoding

- src/os/mac/file.cpp
This PR fixes two issues on macOS
- on macOS, filesystem operations must use UTF8 encoding instead of user-preferred locale (similar issue as #1377)
- on older filesystems, UTF8 normalization is important for uniqueness
This PR introduces a new function createFileSystemRepresentation that uses the correct canonical encoding, prototype chosen to stay as close to the original implementation as possible. This allows replacing multiple lines of code with just one function call in multiple places.
First commit only replaces code in FOpen to demonstrate the change (and because it allows me to close several user reported issues...). Similar changes need to be made in the other filesystem operations (and possibly in other files like dir.cpp).
Thoughts?
> Use normalized UTF8 for filesystem operations

- src/os/mac/utf8conv.cpp
Related to #1377
Clang is giving me two of these warnings:
Comparison of integers of different signs: 'CFIndex' (aka 'long') and 'size_t' (aka 'unsigned long')
I added static_cast<size_t> statements.
> Fix different type warnings

- docs/ReleaseNotes.md
- src/ui/Windows/ControlExtns.cpp
- src/ui/Windows/ControlExtns.h
Per feature request in https://sourceforge.net/p/passwordsafe/feature-requests/921/, this PR allows Ctrl+Backspace to clear the text of any CSecEditExtn control, that is, all controls where password and master passwords are entered/displayed.
The original FR requests this for password database fields, but I don't think this is worth the effort, since the data there can be discovered easily in other places.
> [SF921] Ctrl-Backspace clears password fields (CSecEditExtn controls)

- src/os/mac/utf8conv.cpp
Make sure the input does not contain any NUL characters
Fixes #1387
> CoreFoundation encodes NUL characters (no special treatment)

- docs/ReleaseNotes.md
- src/ui/Windows/AddEdit_PropertyPage.cpp
> Fixed regression, an entry's password history list responds to clicks again

- src/core/CheckVersion.h
- src/core/Command.h
- src/core/DBCompareData.h
- src/core/ExpiredList.h
- src/core/ItemAtt.h
- src/core/ItemData.h
- src/core/PWCharPool.h
- src/core/PWSLog.h
- src/core/PWScore.h
- src/core/PWSdirs.h
- src/core/PWSfileHeader.h
- src/core/PWSprefs.h
- src/core/PolicyManager.h
- src/core/RUEList.h
- src/core/Report.h
- src/core/StringX.h
- src/core/SysInfo.h
- src/core/Util.h
- src/core/VerifyFormat.h
- src/core/XMLprefs.h
- src/core/coredefs.h
- src/core/crypto/AES.h
- src/core/crypto/BlowFish.h
- src/core/crypto/TwoFish.h
- src/core/crypto/sha1.h
- src/core/crypto/sha256.h
This PR fixes the relative paths in the include statements in the header files in core and crypto.
The changes were made easily with these commands (on Mac, sed has slightly different arguments as on Linux):
```
cd core
sed -E -i "" -e 's/include +"os\//include "..\/os\//g' *.h
sed -E -i "" -e 's/include +"core\//include "/g' *.h
cd crypto
sed -E -i "" -e 's/include +"os\//include "..\/..\/os\//g' *.h
```
I understand why the includes worked with the incorrect paths (-I. -I.. -I../..) but that trick does not work for my attempt to package this in a SPM package, which does not offer tricks like this.
And I think it is cleaner to use the correct paths anyway.
This also makes the includes more consistent as e.g. crypto/Fish.h already used
```
#include "../../os/mem.h"
```
> Fix relative include paths

- src/os/mac/utf8conv.cpp
The previous shortcut for dst==NULL was based on the (invalid) assumption that a Unicode character is represented by exactly one 16-bit code unit. This assumption is not correct (https://en.wikipedia.org/wiki/UTF-16).
This PR fixes that by removing the shortcut, so the correct number of wchars is determined and returned.
> Fix UTF32 encoding of characters consisting of two 16-bit code units

- docs/ReleaseNotes.md
- src/core/CoreOtherDB.cpp
- src/core/Item.cpp
- src/core/Item.h
- src/core/PWScore.h
- src/ui/Windows/MainFile.cpp
- version.mfc
Fix for #1408 is currently Windows-only. Needs to be applied to wx as well.
> [GH1408] Update time fields correctly in sync operations

- src/core/ItemAtt.cpp
- src/core/ItemAtt.h
This allows setting the properties when the attachment is not imported. The filepath is probably less relevant in this context, just added for completeness sake.
> Added setters for CItemAtt filename/filepath/mediatype

- src/core/ItemAtt.cpp
- src/core/PWSfileV4.cpp
- src/core/Util.h
- src/test/FileV4Test.cpp
To reproduce, simply add the above file as attachment to a V4 database, close the database and notice that you cannot open it anymore.
This PR fixes the issue by:
- adding another unit test to check this specific case
- adding new inline roundUp inline function to Util.h. Nothing spectacular, but apparently complicated enough to mixup.
Could be deployed in a few other places too (PWScore.cpp and Util.cpp), not done in this PR to keep focus.
- using this function to fix the calculations in src/core/ItemAtt.cpp and src/core/PWSfileV4.cpp
Without this PR, there is a 1:16 chance of not being able to reopen a database after adding an attachment. The database is written correctly, so no risk of a corrupted database, but still not openable without this PR applied.
> V4 rounding issue for files with size multiple of 16 bytes

- src/core/Item.cpp
This PR adds just one fix (commit 382eeb112875b9f0facf73686ad620031abc8c43) to #1420 
As that PR has not been committed yet, it is included here as it references the new roundUp function. I can rebase this PR after #1420 is applied, leaving just the one commit.
An issue in CItem::GetField(const CItemField &field, std::vector<unsigned char> &v) is fixed:
v is correctly resized before decryption, this was only done for small (< BS) lengths, but not for bigger ones.
> Getfield fix

- src/core/PWScore.cpp
- src/core/PWScore.h
- src/ui/Windows/DboxMain.cpp
- src/ui/Windows/MainFile.cpp
- src/ui/Windows/MainFilters.cpp
- src/ui/Windows/MainManage.cpp
- src/ui/Windows/MainView.cpp
- src/ui/Windows/ThisMfcApp.cpp
- src/ui/wxWidgets/DnDFile.cpp
- src/ui/wxWidgets/MenuFileHandlers.cpp
- src/ui/wxWidgets/MenuManageHandlers.cpp
- src/ui/wxWidgets/PWSafeApp.cpp
- src/ui/wxWidgets/PasswordSafeFrame.cpp
The m_bIsOpen ivar is updated internally but currently never used.
From a naming perspective this PR is almost obviously correct, though some code may depend on the old behavior.
Current invocations can be replaced with !GetCurFile().empty() which will make sure everything stays unchanged, but most likely the invokers will want the correct logic.
> Improve naming of IsDbOpen

- src/core/crypto/sha256.cpp
- src/core/crypto/sha256.h
This adds a separate implementation for Mac, almost trivial wrapper around CommonCrypto.
Measurements indicate that this provides 8 to 10 times better performance, allowing the user to select higher Unlock Difficulty, as the unlock speed is almost completely determined by sha256 performance.
> Added sha256 mac using commoncrypto (improved performance)

- Makefile.freebsd
- src/core/Makefile
- src/ui/wxWidgets/wxUtilities.cpp
Port was overdue an update (from 1.12.0 to 1.20.0).
1. `src/core/Makefile` is broken for all builds that use gmake.
2. Yubikey works fine on FreeBSD
3. there's no need to use clang38, not available in FreeBSD ports and builds fine with clang 18.1.6 in base OS.
> Fixes for FreeBSD

- src/core/PWSfileV3.cpp
There are many reasons the FOpen can fail in production scenarios (files being moved, permissions, etc.).
This check makes sure that a proper response is returned instead of continuing (resulting is segmentation fault).
> Properly handle nullptr in release code

- src/core/PWSfileV4.cpp
- src/test/FileV3Test.cpp
- src/test/FileV4Test.cpp
This prevents executing the key stretching twice (one on version detection, one to read the file). It also allows returning wrong_password instead of failure for incorrect passwords.
> Use filename extension to detect V4 database

- src/ui/wxWidgets/Clipboard.cpp
- src/ui/wxWidgets/OptionsPropertySheetDlg.cpp
- src/ui/wxWidgets/PasswordSafeFrame.cpp
- src/ui/wxWidgets/wxUtilities.cpp
- src/ui/wxWidgets/wxUtilities.h
This is a regression from 1.20
PR [#1415](https://github.com/pwsafe/pwsafe/pull/1415) tries to disable all autotype controls when running on a system using Wayland. However, the logic only tests for the absence of X11, so autotype is also disabled on macOS. ~~This PR adds a wxUtilities::IsDisplayManagerWayland() function which is: OS == Linux and not X11.~~. This PR adds a WhatWindowSystem() function to return the type of environment.  The recognized types are: X11, Wayland, macOS, Windows, and Unknown.  The design easily allows other types to be added if and when needed.  Currently, the only use case is to determine when running on a Wayland based system.
> The absence of X11 != Wayland (i.e. macOS)

- src/ui/wxWidgets/AddEditPropSheetDlg.cpp
- src/ui/wxWidgets/AddEditPropSheetDlg.h
Proposed change to db85aa9, because 'm_ItemTotp' already contains the two-factor key the user entered at the Additional tab.
> [wx] TOTP - Proposal to fix error message when copying auth code from an unsaved entry

- .github/workflows/macos-latest.yml
- README.MAC.DEVELOPERS.md
- src/test/Makefile.macos
This PR adds building and running coretest (unit tests) to the macos-latest.yml workflow.
Tested on: (And passed!)
macOS M1Max Sequoia 15.3, Xcode 16.2, wx 3.2.4 and 3.2.6 (local builds)
and the current macOS 14/Xcode 15 GitHub environment.
> [macOS] Add coretest to the macOS workflow

- src/ui/Windows/ControlExtns.cpp
- src/ui/Windows/PWListCtrl.cpp
- src/ui/Windows/PWTreeCtrl.cpp
- src/ui/Windows/PasswordSubsetDlg.cpp
- src/ui/Windows/ProgressPieCtrl.cpp
- src/ui/Windows/ViewReport.cpp
- src/ui/Windows/VirtualKeyboard/VKeyBoardDlg.cpp
instead of hardcoding black and white.
Resolves #1439
> [FR1439] Windows: Use system default text and background colors

- src/core/PWSfileV4.cpp
- src/core/PWSfileV4.h
- src/test/FileV3Test.cpp
1. Define the  min (default) number of hash iterations for V4 files as a fixed fraction of the V3 value, to keep the times comparable.
2. Speedup the FileV3Test.AttachmentTest by using a single file, rather than 8.
> Split min hash iterations

- src/core/ItemData.cpp
- src/core/ItemData.h
Looks like I missed the ! at line 407 of ItemData.h for the new attachment fields.. 🙃
Also added the two non-text fields to CItemData::GetFieldValue for completeness.
> Fixed IsTextField treatment of DATA_ATT_... fields

- src/ui/cli/CMakeLists.txt
- src/ui/cli/search-test.cpp
Works fine on all platforms but Windows.
For some reason, the text resources (cli.rc) links fine into cli, but not the test build.
Disabled on Windows for now.
> Add pwsafe cli test to cmake

- src/ui/wxWidgets/I18N/pos/pwsafe_de.po
With the last update of the translation, an error seems to have occurred in the labeling of the Change button in the password change dialog.
> [wx] Minor correction in German translation

- docs/ReleaseNotesWX.md
- src/ui/wxWidgets/AddEditPropSheetDlg.cpp
- src/ui/wxWidgets/MenuEditHandlers.cpp
- src/ui/wxWidgets/PasswordSafeFrame.h
- version.wx
Addresses #1472 
Also alias should be handled correctly, as well as prep for autotype.
Since 1.21.0 was just released, bumping version to 1.21.1
> [wx gh1472] - Add/Edit Go button now respects [alt] browser

- Xcode/pwsafe-template.plist
- Xcode/pwsafe-xcode6.xcodeproj/project.pbxproj
- src/ui/wxWidgets/PWSafeApp.cpp
- src/ui/wxWidgets/PWSafeApp.h
This adds the file type associations to Info.plist so the pwsafe icon will be used for .psafe3, .psafe4, and .ibak files.  Also, some minor clean-up.
Note: If you double-click on a pwsafe file type it will launch the app, but the name will not be pre-populated in the password dialog.  It's complicated...maybe a project for the future. :-)
> [macOS] Add file type associations

- Xcode/pwsafe-template.plist
- docs/ReleaseNotesWX.md
- src/ui/wxWidgets/MenuFileHandlers.cpp
- src/ui/wxWidgets/PWSafeApp.cpp
- src/ui/wxWidgets/PWSafeApp.h
- src/ui/wxWidgets/PasswordSafeFrame.h
On macOS, when an app is launched by double-clicking a file, the file name is not passed on the command line, as it is in Unix/Linux.  Instead, the file name(s) are passed in event messages which wxWidgets passes to the app by calling these Mac-only functions:
MacNewFile() - When the app icon itself is clicked to launch the program (No file name is passed.)
MacOpenFiles() - When one or more files are double-clicked (we only use the first one in the list)
This is also called if a file is double-clicked while the program is running, in which case it's handled the same as using the File->Open menu item.
However, the framework does not call those functions until OnInit() returns, so MacOpenFiles() does not have a chance to override the default file name displayed in the password entry dialog. …
> [macOS] Support launching the app by clicking a file

- src/ui/wxWidgets/AddEditPropSheetDlg.cpp
Resolves #1469 for non-Mac builds.
> [wx] Rename Cancel button to Close in Add-Edit dialog when Db is read-only

- src/core/ItemField.cpp
This removes the temporary buffer improving
- performance, saves an unnecessary copy
- security, the temporary memory was not cleaned, potentially leaking sensitive data
> Improve CItemField::Get

- src/ui/wxWidgets/AddEditPropSheetDlg.cpp
- src/ui/wxWidgets/PasswordSafeFrame.cpp
I created this as a draft because it still needs to be tested in combination with the auto-lock functionality. It seems to work well with these changes in my environment, but a different environment might exhibit different behavior.
Related to #1470
> [wx] Make message dialog child of Add-Edit dialog

- src/core/ItemData.cpp
This PR fixes two crash reports, so this does happen in the real world.
> Prevent crash on reading invalid safe data

- docs/formatV3.txt
- docs/formatV4.txt
This documents how the stored value must be interpreted, to make sure all platforms work alike.
Reusing a value likely results in a login failure, so it is important that all implementations use the same logic.
> Improve passkey doc

- .gitignore
- Xcode/pwsafe-xcode6.xcodeproj/project.pbxproj
- Xcode/pwsafe-xcode6.xcodeproj/xcshareddata/xcschemes/coretest.xcscheme
- src/core/PWSprefs.cpp
- src/core/PWSprefs.h
- src/os/mac/file.cpp
- src/test/CMakeLists.txt
- src/test/MRUListTest.cpp
- src/test/Makefile.macos
- src/ui/wxWidgets/MenuFileHandlers.cpp
- src/ui/wxWidgets/MenuManageHandlers.cpp
- src/ui/wxWidgets/OptionsPropertySheetDlg.cpp
- src/ui/wxWidgets/PWSafeApp.cpp
- src/ui/wxWidgets/PWSafeApp.h
- src/ui/wxWidgets/PasswordSafeFrame.cpp
- src/ui/wxWidgets/RecentDbList.h
Related to: #1365, #1369, #1371, and #1382
This PR addresses several issues with the Most Recently Used file list:
1. [WX, core] The list is not always kept in MRU order. (A regression left over from #1382)
2. [WX] The config file is re-written on every exit, even if nothing has changed, because the old and new MRU lists are never considered equal.
3. [WX] When a file is opened via the menu, the MRU list in the File menu does not update until the window is minimized/restored.
4. [WX] Debug check failure in wxFileHistory::AddFileToHistory() if the maximum MRU entries option is set to 0. (MaxMRUItems)
5. [WX] Changes to the MRU related settings do not always take effect until a restart or minimize/restore.
6. Added some unit tests for the PWSprefs and RecentDbList MRU list functions …
> Correct some MRU list issues

- src/core/PWSfile.cpp
This will show a more helpful error message ("can't open file" instead of "failure") to the user in case the file cannot be opened for whatever reason (could be permission issue for example).
Note: use a release build to test this change, otherwise an assert stops the program in an earlier stage.
> Improve access denied detection

- src/ui/wxWidgets/AddEditPropSheetDlg.cpp
I noticed this problem crept into 1.21: If I vertically stretch the add/edit dialog, it grows in the wrong place.
Version 1.21 and current master:
Version 1.20 and after this PR is applied to master:
> [wx] Expand the text field on resize of AddEditPropSheetDlg

- src/ui/wxWidgets/wxUtilities.cpp
This warning started to appear with Apple Clang 17 (Xcode 16):
```
.../Xcode/pwsafe/src/ui/wxWidgets/wxUtilities.cpp:558:24: warning: variable length arrays in C++ are a Clang extension [-Wvla-cxx-extension]
558 |   unsigned char buffer[size];
|                        ^~~~
.../Xcode/pwsafe/src/ui/wxWidgets/wxUtilities.cpp:558:24: note: read of non-const variable 'size' is not allowed in a constant expression
.../Xcode/pwsafe/src/ui/wxWidgets/wxUtilities.cpp:552:8: note: declared here
552 |   auto size = itemAttachment.GetContentSize();
|        ^
1 warning generated.
```
If I understand smart pointers properly, this should maintain the original intent while being standards compliant (c++11 and up)
> [wx] Replace variable length array with unique_ptr

- src/core/StringX.cpp
- src/ui/wxWidgets/DragBarCtrl.cpp
- src/ui/wxWidgets/MenuViewHandlers.cpp
- src/ui/wxWidgets/OptionsPropertySheetDlg.cpp
- src/ui/wxWidgets/PWFiltersEditor.cpp
- src/ui/wxWidgets/PasswordSafeFrame.cpp
- src/ui/wxWidgets/wxUtilities.cpp
This reverts commit 4e7ea029cec8bf2da7d4f2e0a813d28544f32e92.
Partial reversion of PR #1520 
This will need to be revisited before migrating to wxWidgets 3.3.0 or later.
> Revert "Remove _() where it's not appropriate"

- src/ui/wxWidgets/PasswordSafeSearch.cpp
Resolves #1543 
Questions:
1. Should the ".  " inserted at line 755 be moved to the strings passed as prefix arguments, so it can be accounted for in their translation?
2. Should the string arguments to wxCHECK_RET, and other debug macros, be flagged for translation?
> [wx] Flag text for translation

- src/ui/wxWidgets/HelpMap.h
- src/ui/wxWidgets/PasswordPolicyDlg.cpp
- src/ui/wxWidgets/PasswordPolicyDlg.h
The PasswordPolicyDlg class does not have the wxWidgets’ RTTI macro specified, so the GetHelpMap() function fails to find the HTML Help page assigned to the dialog.
The RTTI system knows only the nearest base that declares the RTTI info — in this case, wxDialog.
Also, the password_policies.html page is assigned to a non-existing property sheet in Options in HelpMap.h.
This PR is to fix both the issues.
Main Menu > Manage > Password Policies.
Click New or Edit, click Help.
See attached screenshots, hope it helps.
E.g. English: This Help page should be displayed once fixed.
> [wx] Fix PasswordPolicyDlg Help

- src/core/CoreImpExp.cpp
This PR is to fix formatting Report for the Import Text function, in case there are unknown headers in the import file.
The list of unknown columns is not formatted before displaying (no delimiter), so we need to add CRLF after each item as well.
Tested on Windows and Linux, it should work on macOS too.
See attached screenshots how it gets improved.
> Import Text Report - Fix unknown headers formatting

- src/ui/wxWidgets/CryptKeyEntryDlg.cpp
- src/ui/wxWidgets/CryptKeyEntryDlg.h
- src/ui/wxWidgets/ViewReportDlg.cpp
To better reflect the application in question, the Password Safe logo has been added to the key entry dialog. Furthermore, the title bar displays the functionality being called (encryption/decryption), the application name, and the version.
The last commit (7d74e7c) addresses the review [comment](https://github.com/pwsafe/pwsafe/pull/1592#discussion_r2264444158) of @dskrvk in #1592.
> [wx] Modernization of encryption/decryption key entry dialog

- src/ui/wxWidgets/MenuFileHandlers.cpp
If I export a v3 file as a v4 DB, it gets saved with the same filename with the "psafe4" extension.
Then, when using the Save As command for this new v4 file, the default file extension is "psafe3" instead of "psafe4".
The default file name filter is also set to "*.psafe3".
This leads to unintentional overwriting the initial v3 file instead of creating a copy of existing v4 file.
<br>
After the fix is applied:
<br><br>
> [wx] Fix: DBv4 file saved with DBv3 extension when using Save As

- src/ui/wxWidgets/PWSafeApp.cpp
This PR provides a fix to make the program's window minimize to Task Bar (so it’s Alt+Tab-able) in case System Tray becomes not available.
Issue: In many Linux distros, when the System Tray support becomes unavailable (e.g. due to migration to Wayland), Password Safe's window on locking the database behaves like it disappears:
In this case, there’s no Tray or Task Bar icon for user to click to restore the window.
Since the minimized window is unmapped/hidden, it also doesn’t show up in Alt+Tab or when using the compositor's task switcher.
Then, user can only kill existing process of Password Safe and start the program again.
A confused user would most probably launch Password Safe again trying to open the same database, only to be prompted with an error message: "Lock is done by …
> [wx] Fix minimize to System Tray on Linux
