pwsafe/pwsafe

src/core/ItemAtt.cpp
src/core/ItemAtt.h
src/core/ItemData.h
src/ui/Windows/AddEdit_Attachment.cpp
src/ui/Windows/AdvancedDlg.cpp
src/ui/Windows/AdvancedDlg.h
src/ui/Windows/AdvancedValues.h
src/ui/Windows/DboxMain.h
src/ui/Windows/MainView.cpp
src/ui/Windows/PWFindToolBar.cpp
src/ui/Windows/PWFindToolBar.h
src/ui/Windows/res/PasswordSafe3.rc2
src/ui/Windows/resource3.h

(Need to fix that Find no longer saves user selection within the same session)

Implement Find support for attachment filename

---

src/core/ItemAtt.cpp
src/os/file.h
src/os/linux/file.cpp
src/os/mac/file.cpp
src/os/windows/file.cpp
src/ui/Windows/AddEdit_Attachment.cpp

Compiles and works on MFC
Compiles wxWidgets (WIndows using VS2015) but can't test as the wxWIdgets UI doesn't yet support attachments

Re-factor file time code

---

src/ui/cli/Makefile

Specify c++11, link with core twice to satisfy libos, fix an apparent typo in "clean" target.

Fix cli build

---

Xcode/pwsafe-xcode6.xcodeproj/project.pbxproj
Xcode/pwsafe-xcode6.xcodeproj/xcshareddata/xcschemes/pwsafe-debug.xcscheme
Xcode/pwsafe-xcode6.xcodeproj/xcshareddata/xcschemes/pwsafe.xcscheme
Xcode/pwsafe.plist
src/os/mac/media.cpp

* Add missing files to Xcode project
* Implement trivial (always return "unknown") pws_os::GetMediaType
* Update Xcode project to latest Xcode recommendations

Restore build on mac

---

.gitignore
docs/ReleaseNotes.html
docs/ReleaseNotes.txt
src/core/PWScore.cpp
src/ui/Windows/MainEdit.cpp

Please update SF BR and mark "pending" - Thanks

Fix BR 1330

---

src/ui/Windows/I18N/pos/pwsafe_de.po

There's a typo in the German translation.
This pull request fixes the typo.

Fixed typo in German translation.

---

Xcode/pwsafe-xcode6.xcodeproj/project.pbxproj
src/core/Makefile
src/ui/wxWidgets/Makefile

Breakage caused by moving of RUEList.{h,cpp} to src/core, and the new mainView.cpp being missing from Makefile

Fix osx & linux builds

---

src/ui/wxWidgets/dragbar.cpp
src/ui/wxWidgets/wxutils.h

In my case DnD into Firefox doesn't work. The reason was incorrect (?) object type.

[wx] Try to fix DnD into Firefox

---

CodeLite/core.project
CodeLite/pwsafe.project

Moved RUEList.* to core, and added new mailView.cpp to wxWidgets

Fix CodeLite (linux) build

---

README.MAC.DEVELOPERS.txt

This just makes the steps a little easier to follow.

Fix minor errors in README.MAC.DEVELOPERS.txt

---

src/ui/Windows/ColumnChooserLC.cpp
src/ui/Windows/ColumnChooserLC.h
src/ui/Windows/DropSource.cpp
src/ui/Windows/DropSource.h
src/ui/Windows/LVHdrCtrl.cpp
src/ui/Windows/LVHdrCtrl.h

Reported ASSERT in CmdTarget, although I could not reproduce it
ASSERT is in the same place as I had in TreeCtrl but I couldn't reproduce it - so changed anyway
to be like TreeCtrl

Change List view column picker D&D to be like Tree list

---

docs/ReleaseNotes.html
docs/ReleaseNotes.txt
src/ui/Windows/DboxMain.h
src/ui/Windows/MainView.cpp
src/ui/Windows/PWFindToolBar.cpp

No idea why commits are there twice!

Fix Find toolbar issues

---

src/os/windows/UUID.cpp

- security software with socket headers makes me uneasy...
- compiled with Visual Studio 2015

Removed an unneeded Winsock include

---

docs/formatV3.txt
docs/formatV4.txt
src/test/CommandsTest.cpp
src/test/FileV3Test.cpp

Fix typo
Update formatV3.txt & formatV4.txt to remove ambiguity

Add extra tests for refactor of UpdatePasswordCommand

---

src/core/Command.cpp
src/core/Command.h
src/core/CommandInterface.h
src/core/PWScore.cpp
src/core/PWScore.h
src/core/UIinterface.h
src/ui/Windows/DboxMain.h
src/ui/Windows/MainView.cpp
src/ui/Windows/PWTreeCtrl.h
src/ui/Windows/ThisMfcApp.cpp
src/ui/Windows/res/PasswordSafe3.rc2
src/ui/wxWidgets/passwordsafeframe.cpp
src/ui/wxWidgets/passwordsafeframe.h

Add support for entry/group highlighting (if enabled) via commands
Update Status bar tooltip
Note: First change is quite extensive but is the basis for future use (currently only modified nodes)

Add support for entry/group highlighting (if enabled) via commands

---

src/core/XMLprefs.cpp
src/os/windows/KeySend.cpp
src/ui/Windows/AddEdit_Basic.cpp
src/ui/Windows/DDStatic.cpp
src/ui/Windows/MainMenu.cpp
src/ui/Windows/ManagePSWDPols.cpp
src/ui/Windows/PasskeyChangeDlg.cpp
src/ui/Windows/PasskeyEntry.cpp
src/ui/Windows/PasskeySetup.cpp
src/ui/Windows/PasswordPolicyDlg.cpp
src/ui/Windows/PasswordSubsetDlg.cpp
src/ui/Windows/PasswordSubsetDlg.h
src/ui/Windows/Shortcut.cpp
src/ui/Windows/TBMStatic.cpp
src/ui/Windows/VirtualKeyboard/VKeyBoardDlg.cpp
src/ui/Windows/WZSelectDB.cpp
src/ui/Windows/Windowsdefs.h

Fix issue with Add/Edit Notes when word wrap is set.

---

src/ui/wxWidgets/I18N/Makefile
src/ui/wxWidgets/I18N/pos/pwsafe_hu.po

Hello!
These are far from complete, but at least the GUI elements (except the synchronization and YubiKey dialogs) are translated.

Add some Hungarian translations.

---

src/ui/Windows/MainEdit.cpp

A bit more than just fix 64-bit warning - this is the correct way to go from POSITION to integer

Fix 64-bit warnings

---

src/core/PWScore.cpp
src/core/PWScore.h
src/ui/Windows/MainManage.cpp
src/ui/wxWidgets/mainManage.cpp
src/ui/wxWidgets/optionspropsheet.cpp
src/ui/wxWidgets/optionspropsheet.h

Implements the functionality required by the Password History tab on the
options window.

[wx] Implement Password History Options

---

Xcode/pwsafe-xcode6.xcodeproj/project.pbxproj

by defining NO_QR in Xcode project, for now

Fix OSX build (using Xcode)

---

help/pwsafeRU/pwsafeRU.hhc
install/windows/I18N/pwsafe_ru.lng
install/windows/I18N/pwsafe_tr.lng

Attempt to fix some encoding issues

Russina codepage fixes

---

src/ui/wxWidgets/passwordsubset.cpp

Add explicit casts where required.
Fixes #378

Fix build failures with wxgtk 3.0.3.1

---

src/ui/wxWidgets/I18N/pos/pwsafe_de.po

Update of wxWidgets translation.

Update of German translation.

---

src/ui/wxWidgets/optionspropsheet.cpp

Remove of wxSUNKEN_BORDER for all wxPanel.
Minor layout improvements.

Improve wx based options dialog

---

src/ui/wxWidgets/safecombinationentry.cpp

Combobox for file selection is now expandable to give users the opportunity
to enlarge the dialog to make the full path and selected file visible.
Controls are more align to each other.

Improve layout of wx based SafeCombinationEntry dialog

---

src/core/Item.cpp
src/core/Item.h
src/core/ItemAtt.cpp
src/core/ItemData.cpp
src/core/ItemData.h
src/core/ItemField.cpp
src/core/PWSAuxParse.cpp
src/core/PWSFilters.cpp
src/core/PWScore.cpp
src/core/PWSfileV3.cpp
src/core/PWSfileV4.cpp
src/core/PWSfileV4.h
src/core/PWSprefs.cpp
src/core/Util.cpp
src/core/XMLprefs.cpp
src/os/unix/dir.cpp
src/os/unix/file.cpp
src/ui/wxWidgets/CompareDlg.cpp
src/ui/wxWidgets/ManagePwdPolicies.cpp
src/ui/wxWidgets/PWSgrid.cpp
src/ui/wxWidgets/PWSgrid.h
src/ui/wxWidgets/PWStree.cpp
src/ui/wxWidgets/PwsSync.cpp
src/ui/wxWidgets/RecentDBList.h
src/ui/wxWidgets/addeditpropsheet.cpp
src/ui/wxWidgets/mainEdit.cpp
src/ui/wxWidgets/optionspropsheet.cpp
src/ui/wxWidgets/pwsmenushortcuts.cpp
src/ui/wxWidgets/safecombinationentry.cpp
xml/pwsafe.xsd

Testing done: ran the program on a new safe file, used the main features.

Refactoring for brevity & small optimizations

---

CMakeLists.txt
src/os/unix/dir.cpp

Adjust path in dir.cpp and CMakeLists.txt

Adjust path to help and xml directory to where they belong on Linux.

---

src/ui/wxWidgets/ManagePwdPolicies.cpp

- Correctly layout the dialog also if only default policy is present
- Prevent delayed layout update on resize events for better visual appearance
- Make tables read only instead each single cell
- Update button states according to selection
- Remove macro UNREFERENCED_PARAMETER for parameters that are used

Minor layout improvements on policies dialog

---

CodeBlocks/core/core.cbp
CodeBlocks/os/os.cbp
CodeBlocks/pwsafe/pwsafe.cbp

- few options moved to root config
- added new files

Some updats for C::B project

---

src/core/StringX.cpp
src/ui/wxWidgets/ManagePwdPolicies.cpp
src/ui/wxWidgets/PasswordPolicy.cpp

I have had compilation errors because of missing copy constructor/operator= at StringX for wxString.

[wx] Fixed compilation issues (gcc-7.3.0)

---

src/ui/wxWidgets/properties.cpp
src/ui/wxWidgets/properties.h

- Number of attachments
- Date when master password was last changed
- Database name
- Database description

[wx] Show more properties at properties dialog

---

src/os/mac/dir.cpp
src/os/unix/dir.cpp

This resolves #1136 and #1153.

[wx] Consider symbolic links

---

src/os/unix/cleanup.cpp

Resolves reported issue [#1242](https://sourceforge.net/p/passwordsafe/bugs/1242) on SourceForge.

[wx] Close application properly on receipt of SIGHUP

---

src/ui/wxWidgets/about.cpp

Debug output about received data only in error cases.

[wx] Minor improvements to Version Check fix

---

Xcode/pwsafe-xcode6.xcodeproj/project.pbxproj
src/ui/cli/Makefile

Mostly, 'core' now depends on wxWidgets

Fix non-cmake builds on OSX/Linux

---

src/ui/wxWidgets/I18N/pos/pwsafe_hu.po

Adding a set of missing Hungarian translations. Some items were relocated by poedit within the file so the change looks quite bigger than it really is.

Adding a set of missing Hungarian translations

---

src/ui/wxWidgets/I18N/pos/pwsafe_hu.po

Adding new/updated Hungarian translations

Adding new/updated Hungarian translations

---

src/ui/wxWidgets/passwordsafeframe.cpp
src/ui/wxWidgets/passwordsafeframe.h

Resolves reported issue [1484](https://sourceforge.net/p/passwordsafe/bugs/1484).

[wx] Show recently used DBs on File menu

---

src/ui/wxWidgets/mainEdit.cpp

Resolves [1486](https://sourceforge.net/p/passwordsafe/bugs/1486/)

[wx] Expand implementation of RunCommand

---

src/ui/wxWidgets/optionspropsheet.cpp
src/ui/wxWidgets/optionspropsheet.h

[wx] Refactoring of Options Dialog Members

---

src/os/typedefs.h
src/ui/Windows/DboxMain.cpp
src/ui/Windows/DboxMain.h
src/ui/Windows/MainView.cpp
src/ui/Windows/PWDialog.cpp

Implemented DPI scaling for the dialogs under Windows 10.

Win10uiscaling

---

install/slackware/passwordsafe.SlackBuild

Minor change to force regeneration of version.h

[wx] SlackBuild update

---

src/ui/wxWidgets/about.cpp

also suppressed warning about unused userData

[wx] fixed enumeration of curlVersion->protocols

---

src/ui/wxWidgets/passwordsafeframe.cpp
src/ui/wxWidgets/passwordsafeframe.h

**New Shortcuts**
- Ctrl + J : Locks Db
- Ctrl + I : Unlocks Db
Resolves #549

[wx] Add menu item 'Unlock Safe'

---

src/ui/wxWidgets/mainEdit.cpp
src/ui/wxWidgets/passwordsafeframe.cpp

Resolves reported [issue](https://sourceforge.net/p/passwordsafe/discussion/134801/thread/e9c02956e0/?limit=25#af1c) on SourceForge.

[wx] Save view state on minimize

---

src/ui/wxWidgets/CryptKeyEntry.cpp
src/ui/wxWidgets/about.cpp

[Issue](https://sourceforge.net/p/passwordsafe/discussion/134800/thread/7edafb8280/) was reported at SourceForge.

[wx] Resolve build errors on openSUSE

---

src/ui/wxWidgets/addeditpropsheet.cpp

Motivated by [1493](https://sourceforge.net/p/passwordsafe/bugs/1493/).

Improvements at Policy Handling

---

CodeBlocks/core/core.cbp
CodeBlocks/os/os.cbp
CodeBlocks/pwsafe/pwsafe.cbp
CodeBlocks/wx-config-filter
CodeBlocks/wx-config-filter32

- missing files and dependecies
- request wx 3.0 (useful for installations with multiple wx versions)
- group warning settings

[wx] C::B updates

---

CMakeLists.txt
CMakeModules/FindMagic.cmake

Update CMakeLists regarding 'Magic' library

---

src/ui/wxWidgets/AddEditPropSheetDlg.cpp
src/ui/wxWidgets/AddEditPropSheetDlg.h

As preparation for the integration of 'Attachment' tab.

[wx] Code refactoring of 'AddEditPropSheetDlg'

---

src/ui/wxWidgets/PasswordSafeFrame.cpp
src/ui/wxWidgets/TreeCtrl.cpp
src/ui/wxWidgets/TreeCtrl.h

Resolves reported issue [1217](https://sourceforge.net/p/passwordsafe/bugs/1217/).

[wx] Improve context menu handling at tree view

---

src/ui/wxWidgets/DragBarCtrl.cpp
src/ui/wxWidgets/DragBarCtrl.h
src/ui/wxWidgets/DragBarGenericCtrl.cpp
src/ui/wxWidgets/DragBarGenericCtrl.h

In the hope that easier to use for people that are visually impaired.

[wx] Increase margins of dragbar icons

---

README.LINUX.md

There has been an ebuild (pacakge) for Gentoo since 2016. It's about time it gets listed ;-)

Added info about Gentoo to README.LINUX.md

---

src/ui/wxWidgets/I18N/pos/pwsafe_hu.po

Updates for Hungarian translations

Updates for Hungarian translations

---

README.LINUX.DEVELOPERS.md

You can use yum/dnf localinstall to install rpm files

Use dnf instead of rpm [iU]vh

---

src/ui/wxWidgets/TreeCtrl.cpp
src/ui/wxWidgets/TreeCtrl.h

[wx] Fix sorting in tree view

---

src/ui/wxWidgets/OptionsPropertySheetDlg.cpp
src/ui/wxWidgets/OptionsPropertySheetDlg.h

Same as already done for 'AddEditPropSheetDlg', which makes navigation in the source code easier.

[wx] Refactor 'CreateControls' of 'OptionsPropertySheetDlg'

---

src/ui/wxWidgets/PasswordSafeFrame.cpp

[wx] Relax the rules for adding a password item

---

src/ui/wxWidgets/OptionsPropertySheetDlg.cpp
src/ui/wxWidgets/OptionsPropertySheetDlg.h

[wx] Add title to tabs of options dialog

---

src/ui/wxWidgets/SafeCombinationEntryDlg.cpp

Could someone please check if this solves issue #674 ?

[wx] SafeCombinationEntryDlg: Resolve issue on Fedora of not appearing buttons

---

src/ui/wxWidgets/CompareDlg.cpp
src/ui/wxWidgets/DbSelectionPanel.cpp
src/ui/wxWidgets/ExportTextWarningDlg.cpp
src/ui/wxWidgets/I18N/pos/pwsafe_de.po
src/ui/wxWidgets/SafeCombinationChangeDlg.cpp
src/ui/wxWidgets/SafeCombinationCtrl.cpp
src/ui/wxWidgets/SafeCombinationCtrl.h
src/ui/wxWidgets/SafeCombinationEntryDlg.cpp
src/ui/wxWidgets/SafeCombinationPromptDlg.cpp
src/ui/wxWidgets/YubiMixin.cpp
src/ui/wxWidgets/wxUtilities.h

Since I don't have a YubiKey, I was not able to verify how the layout changes would affect the YubiKey-related controls.

Add 'Show Combination' to dialogs

---

src/ui/wxWidgets/SafeCombinationEntryDlg.cpp
src/ui/wxWidgets/SafeCombinationEntryDlg.h

_   _
| | | | __ _ _ __  _ __  _   _
| |_| |/ _` | '_ \| '_ \| | | |
|  _  | (_| | |_) | |_) | |_| |
|_| |_|\__,_| .__/| .__/ \__, |
|_|   |_|    |___/
_   _                __   __
| \ | | _____      __ \ \ / /__  __ _ _ __
|  \| |/ _ \ \ /\ / /  \ V / _ \/ _` | '__|
| |\  |  __/\ V  V /    | |  __/ (_| | |
|_| \_|\___| \_/\_/     |_|\___|\__,_|_|
____   ___ ____  _
|___ \ / _ \___ \/ |
__) | | | |__) | |
/ __/| |_| / __/| |
|_____|\___/_____|_|

Shorten the file path name in 'SafeCombinationEntryDlg'

---

CMakeLists.txt

Closes: #721
Is working as expected.

add cmake option GTEST_BUILD to control gtest download and build on-fly

---

src/core/Util.cpp
src/core/core.rc2

[wx] Add missing string for IDSC_DRAGNUMBER to 'core.rc2'

---

Makefile.macos
README.MAC.DEVELOPERS.md

No I reset my fork and did update of needed file again. Cross the finger that now we can correct. Thank you for your patience.

Update for correct build in Xcode for macOS and update MAC-Readme

---

src/ui/wxWidgets/CompareDlg.cpp
src/ui/wxWidgets/MenuManageHandlers.cpp
src/ui/wxWidgets/PasswordSafeSearch.cpp
src/ui/wxWidgets/PasswordSafeSearch.h

Including this proposed changes the wxWidgets 3.0.5 and 3.1.4 is able to compile and link on Debian Buster Raspberry Pi Desktop.
The changes in PasswordSafeSearch can be overtaken for all environment, at least on MacOS they perform well. I did not changed as long not having feedback from other platforms.
The fix will close issue #729.

Make Debian Buster GTK 3.0 able to compile.

---

src/core/Command.cpp
src/ui/wxWidgets/TreeCtrl.cpp
src/ui/wxWidgets/graphics/empty_node.xpm
src/ui/wxWidgets/graphics/empty_node_dark.xpm

Show different Item icon in tree view for entries that will be shortly expired (warning) or are expired.

Implement issue #734

---

Misc/I18N/ru/omegat_help/omegat/project_save.tmx
Misc/I18N/ru/omegat_help/omegat_help-level1.tmx
Misc/I18N/ru/omegat_help/omegat_help-level2.tmx
Misc/I18N/ru/omegat_help/omegat_help-omegat.tmx
Misc/I18N/ru/omegat_wx/omegat/project_save.tmx
Misc/I18N/ru/omegat_wx/omegat_wx-level1.tmx
Misc/I18N/ru/omegat_wx/omegat_wx-level2.tmx
Misc/I18N/ru/omegat_wx/omegat_wx-omegat.tmx
src/ui/Windows/I18N/pos/pwsafe_ru.po
src/ui/wxWidgets/I18N/pos/pwsafe_ru.po
src/ui/wxWidgets/PWFiltersEditor.cpp
src/ui/wxWidgets/SelectionCriteria.cpp

also fixed translation for compare action in report (wx)

[i18n] Updates in Russian texts

---

Misc/I18N/ru/omegat_wx/omegat/project_save.tmx
Misc/I18N/ru/omegat_wx/omegat_wx-level1.tmx
Misc/I18N/ru/omegat_wx/omegat_wx-level2.tmx
Misc/I18N/ru/omegat_wx/omegat_wx-omegat.tmx
src/ui/Windows/I18N/pos/pwsafe_ru.po
src/ui/wxWidgets/I18N/pos/pwsafe_ru.po

Few more updates for upcoming release

[i18n] Updates in Russian .po

---

install/macosx/Makefile
src/ui/wxWidgets/I18N/pos/pwsafe_da.po
src/ui/wxWidgets/I18N/pos/pwsafe_de.po
src/ui/wxWidgets/I18N/pos/pwsafe_es.po
src/ui/wxWidgets/I18N/pos/pwsafe_fr.po
src/ui/wxWidgets/I18N/pos/pwsafe_hu.po
src/ui/wxWidgets/I18N/pos/pwsafe_it.po
src/ui/wxWidgets/I18N/pos/pwsafe_ko.po
src/ui/wxWidgets/I18N/pos/pwsafe_nl.po
src/ui/wxWidgets/I18N/pos/pwsafe_pl.po
src/ui/wxWidgets/I18N/pos/pwsafe_ru.po
src/ui/wxWidgets/I18N/pos/pwsafe_sv.po
src/ui/wxWidgets/I18N/pos/pwsafe_zh.po

Update language files for Germany and adapt the Makefile for dmg-package generation to be universal - no adaptation needed in the future.

Update dmg package generation

---

src/ui/wxWidgets/SelectAliasDlg.cpp
src/ui/wxWidgets/TreeCtrl.cpp

[wx] Replace all occurrences of deprecated 'wxYield' with 'wxSafeYield'

---

src/core/crypto/bitops.h

Add loongarch64 info

---

src/ui/Windows/I18N/pwsafe.pot

Fix some small issues in source language (english) file. Can I remove the duplicate lines too and only keep the line around 5858?

Fix some formatting issues in english language file

---

src/ui/wxWidgets/I18N/pos/pwsafe_de.po

Update german translation for wx version. Typos, wordings, little improvements here and there.

[wx] Update german translation

---

install/macosx/Makefile

The WXDIR building is updated to handle update coming from adaption in generate-configs adding -L/usr/local/lib

Adapt to handle update of xcodeproj-file in Xcode directory (adding of home-brew path).

---

src/ui/wxWidgets/PasswordSafeFrame.cpp

Resolves #829.
Also added grid refresh after font changes so that the change is reflected immediately.

[wx] Apply tree colors to grid colors (when using a dark theme)

---

src/ui/Windows/PasswordSafe.rc
src/ui/wxWidgets/MenuEditHandlers.cpp

This pull request implements the "Confirm copying of password to clipboard" option setting.

[wx] Add confirmation dialog to copy password

---

CMakeLists.txt
CMakeModules/FindMagic.cmake
Misc/setup-linux-dev-env.sh

This is an attempt to resolve the RPM dependecies reported in #840.
Unfortunately untested due to general problems with the build under openSUSE.

[wx] Distinguish between openSUSE and Fedora in RPM packaging

---

src/core/Util.cpp

Since the output of the first two calls to memset are not read before the last call, those first two calls can be skipped by the compiler. For example, clang-15 only calls the last memset():
https://godbolt.org/z/fzvKxqqhf
Combine the existing approach with OpenSSL's use of calling memset() through a volatile function pointer.  On Win32, use SecureZeroMemory() for zeroisation, since it is designed for that purpose.
https://github.com/openssl/openssl/blob/master/crypto/mem_clr.c

trashMemory() only calls the last std::memset().

---

src/Tools/Windows/I18N/ResText/Resource.h

The file followed a novel CR-CR-LF (0x0d 0x0d 0x0a) EOL convention.
```
~/src/crypto/pwsafe$ git show origin/master:src/Tools/Windows/I18N/ResText/Resource.h | hexdump -C
00000000  2f 2f 7b 7b 4e 4f 5f 44  45 50 45 4e 44 45 4e 43  |//{{NO_DEPENDENC|
00000010  49 45 53 7d 7d 0d 0d 0a  2f 2f 20 4d 69 63 72 6f  |IES}}...// Micro|
00000020  73 6f 66 74 20 56 69 73  75 61 6c 20 43 2b 2b 20  |soft Visual C++ |
00000030  67 65 6e 65 72 61 74 65  64 20 69 6e 63 6c 75 64  |generated includ|
00000040  65 20 66 69 6c 65 2e 0d  0d 0a 2f 2f 20 55 73 65  |e file....// Use|
00000050  64 20 62 79 20 52 65 73  54 65 78 74 2e 72 63 0d  |d by ResText.rc.|
00000060  0d 0a 2f 2f 0d 0d 0a 0d  0d 0a 2f 2f 20 4e 65 78  |..//......// Nex|
00000070  74 20 64 65 66 61 75 6c  74 20 76 61 6c 75 65 73  |t default …
```

Fix strange EOLs in Resource.h.

---

src/Tools/Windows/I18N/ResText/Utils.cpp
src/core/core.rc2
src/ui/Windows/I18N/pwsafe.pot
src/ui/Windows/res/PasswordSafe2.rc2
src/ui/Windows/res/PasswordSafe3.rc2

This reverts part of commit f75908ede6691d77c69248dd87c0d7ccfc58aa23

Revert clobbered text change in PasswordSafe2.rc2.

---

src/ui/Windows/version.in

Add the "[D]" on debug builds (not the other way around).

"[D]" is for debug.

---

.github/workflows/macos-latest.yml
Xcode/pwsafe-xcode6.xcodeproj/project.pbxproj

If this will not work on 13.x Ventura, consider moving to 10.15 (Catalina).

macOS: Change deployment target and minimum OS version to 10.14 (Mojave)

---

src/ui/wxWidgets/PasswordSafeSearch.cpp

[wx] Fix repeated search with enter key

---

src/ui/Windows/I18N/pos/pwsafe_de.po

Based on the correction suggestions in 780f98c.

[i18n] Minor corrections to german translation in pwsafe_de.po

---

README.FREEBSD.md
README.LINUX.DEVELOPERS.md
README.LINUX.md
README.MAC.DEVELOPERS.md
README.OPENBSD.md
README.XML.md
README.md

I have cleansing some of the .md files and added some new info in it.
Also cleansed branding from PasswordSafe to Password Safe.

GitHub project web pages updates

---

.github/workflows/cmake-build.yml
.github/workflows/codeql-analysis.yml
.github/workflows/macos-latest.yml
.github/workflows/ubuntu-latest.yml

Cleans up warnings in workflow action logs.

update github actions to use latest 3rd party stuff

---

src/ui/Windows/res/PasswordSafe3.rc2
src/ui/wxWidgets/AboutDlg.cpp

Help About dialog:
- Fix click "here" issue.
- Changes few "PasswordSafe" with "Password Safe"

Small improvements on Help About

---

README.LINUX.DEVELOPERS.md

Updated command for Ninja compiler.

Update compiler command for Linux Developers

---

README.LINUX.FLATPAK.md

Instructions to build Password Safe as flatpak package on Linux

Add new file with how to build flatpak instructions

---

src/ui/Windows/res/PasswordSafe3.rc2
src/ui/wxWidgets/PropertiesDlg.cpp

File | Properties. Simplify title.

Simplify File Properties title dialogs

---

src/ui/Windows/res/PasswordSafe3.rc2
src/ui/wxWidgets/ImportTextDlg.cpp
src/ui/wxWidgets/ImportXmlDlg.cpp
src/ui/wxWidgets/MenuFileHandlers.cpp

File | Import. Simplify sting names.

Simplifty File Import dialog strings

---

src/ui/wxWidgets/SelectAliasDlg.cpp

[wx] Improve layout of alias selection dialog

---

src/ui/wxWidgets/AddEditPropSheetDlg.cpp
src/ui/wxWidgets/AddEditPropSheetDlg.h

[wx] Fix labeling of Show/Hide button in Add/Edit dialog for Alias

---

src/ui/wxWidgets/AddEditPropSheetDlg.cpp

[wx] Update text control style flags in wxGtk build without replacing text control

---

src/ui/wxWidgets/SafeCombinationEntryDlg.cpp
src/ui/wxWidgets/SafeCombinationEntryDlg.h
src/ui/wxWidgets/SafeCombinationPromptDlg.cpp
src/ui/wxWidgets/SafeCombinationPromptDlg.h

[wx] Do not exit after entering the wrong password several times

---

src/ui/wxWidgets/AddEditPropSheetDlg.cpp

[wx] Change button labels of Add-Entry-Cancel dialog

---

.github/workflows/macos-latest.yml

This PR makes the following changes to the macOS yaml file:
- Use the new macos-14 runner (required adding sudo to make install)
- Xcode 15.3
(Other changes have been split into their own PRs.)

Upgrade macOS build to the new macos-14 runner

---

src/ui/wxWidgets/PasswordPolicyDlg.cpp
src/ui/wxWidgets/PasswordPolicyDlg.h

[wx] Fix status update of policy dialog controls

---

src/ui/wxWidgets/DbSelectionPanel.cpp

[wx] Remove 'Show Master Password' checkbox from Merge and Compare dialog

---

src/ui/wxWidgets/QueryCancelDlg.cpp

[wx] Rename 'Yes/No' buttons to 'Discard/Cancel' in Password Policy dialog

---

src/ui/wxWidgets/QueryCancelDlg.cpp

Changed based on ronys comment https://github.com/pwsafe/pwsafe/pull/1260#issuecomment-2098933205

[wx] Change button style flags from 'Yes/No' to 'Ok/Cancel' in QueryCancelDlg

---

src/ui/wxWidgets/AddEditPropSheetDlg.cpp
src/ui/wxWidgets/CreateShortcutDlg.cpp
src/ui/wxWidgets/MenuEditHandlers.cpp
src/ui/wxWidgets/TreeCtrl.cpp
src/ui/wxWidgets/TreeCtrl.h

[wx] Fix group handling

---

src/ui/wxWidgets/MenuFileHandlers.cpp
src/ui/wxWidgets/SafeCombinationEntryDlg.cpp
src/ui/wxWidgets/SafeCombinationSetupDlg.cpp
src/ui/wxWidgets/SafeCombinationSetupDlg.h

Related to #1277 
Resolves #1273 
Resolves #1274

[wx] Modernization of Password Setup Dialog

---

src/ui/wxWidgets/SafeCombinationChangeDlg.cpp
src/ui/wxWidgets/SafeCombinationEntryDlg.cpp
src/ui/wxWidgets/YubiMixin.cpp
src/ui/wxWidgets/YubiMixin.h
src/ui/wxWidgets/wxUtilities.cpp

Related to #1288, #1245, #1247

[wx] Reserve space for Yubi controls to prevent dialog resizing

---

Makefile.windows
README.CMAKE.md
docs/ReleaseNotes.md
docs/ReleaseNotesWX.md
help/default/html/autotype.html
src/core/ItemData.cpp
src/core/ItemData.h
src/core/PWSAuxParse.cpp
src/core/PWSAuxParse.h
src/test/AliasShortcutTest.cpp
src/test/AuxParseTest.cpp
src/ui/Windows/AddEdit_Additional.cpp
src/ui/Windows/AddEdit_Basic.cpp
src/ui/Windows/DboxTray.cpp
src/ui/Windows/MainEdit.cpp
src/ui/wxWidgets/MenuEditHandlers.cpp

Fr1301: Support autotype of TOTP auth code

---

src/ui/wxWidgets/SafeCombinationEntryDlg.cpp
src/ui/wxWidgets/SafeCombinationEntryDlg.h
src/ui/wxWidgets/SafeCombinationPromptDlg.cpp
src/ui/wxWidgets/SafeCombinationPromptDlg.h

Resolves #1331.
Resolves #1332.

File path display

---

src/ui/wxWidgets/PasswordSafeFrame.cpp

[wx] Rename menu entry from 'Recent Safes' to 'Recent Databases'

---

src/ui/wxWidgets/ExportTextWarningDlg.cpp

See #1352 for current version of the export dialog(s).
Resolves #1352

[wx] Update of Export dialog

---

src/core/PWSprefs.cpp

[BR1361] Fix core dump on Manjaro

---

docs/ReleaseNotesWX.md
src/ui/wxWidgets/HelpMap.h
src/ui/wxWidgets/OptionsPropertySheetDlg.cpp
src/ui/wxWidgets/OptionsPropertySheetDlg.h

#1374 
- Fixed broken misc help
- Handle browser command line arguments preference correctly.

BR1374 - wx misc preference issues

---

src/ui/wxWidgets/OptionsPropertySheetDlg.cpp

Resolves #1394 
Resolves #1395

Add 'Not Implemented' text

---

docs/ReleaseNotesWX.md
version.wx

Wx 1.20 release

---

src/ui/wxWidgets/AddEditPropSheetDlg.cpp
src/ui/wxWidgets/OptionsPropertySheetDlg.cpp
src/ui/wxWidgets/PasswordSafeFrame.cpp
src/ui/wxWidgets/wxUtilities.cpp
src/ui/wxWidgets/wxUtilities.h

[wx] Disable Autotype controls on Wayland

---

src/ui/wxWidgets/AddEditPropSheetDlg.cpp

[wx] TOTP - Fix handling of changes in Add-Edit dialog

---

src/ui/wxWidgets/AddEditPropSheetDlg.cpp
src/ui/wxWidgets/Clipboard.cpp
src/ui/wxWidgets/PasswordSafeFrame.cpp

[wx] TOTP - Abort periodic copying to the clipboard if the content has been changed by another application

---

src/ui/wxWidgets/AddEditPropSheetDlg.cpp
src/ui/wxWidgets/PasswordSafeFrame.cpp

Minor optimizations based on the suggestions ([comment 1](https://github.com/pwsafe/pwsafe/pull/1456#discussion_r1974932441) and [comment 2](https://github.com/pwsafe/pwsafe/pull/1456#discussion_r1974957421)) in #1456.

[wx] TOTP - Check for changes in the clipboard before copying the auth code

---

src/ui/cli/CMakeLists.txt

Addresses flatpak regression described in #1467

don't build cli test if NO_GTEST is set

---

src/ui/wxWidgets/CryptKeyEntryDlg.cpp

[wx] Fix CryptKeyEntryDlg layout issue on Wayland

---

help/pwsafeDE/html/autotype.html

\m now translated to German
\2 added 
\o wrongt intend fixed

German Translation: autotype.html added \2

---

src/core/PWCharPool.cpp
src/core/PWCharPool.h
src/ui/wxWidgets/AddEditPropSheetDlg.cpp
src/ui/wxWidgets/AddEditPropSheetDlg.h
src/ui/wxWidgets/CMakeLists.txt
src/ui/wxWidgets/Makefile
src/ui/wxWidgets/SafeCombinationChangeDlg.cpp
src/ui/wxWidgets/SafeCombinationChangeDlg.h
src/ui/wxWidgets/SafeCombinationCtrl.cpp
src/ui/wxWidgets/SafeCombinationCtrl.h
src/ui/wxWidgets/SafeCombinationSetupDlg.cpp
src/ui/wxWidgets/SafeCombinationSetupDlg.h
src/ui/wxWidgets/StrengthMeter.cpp
src/ui/wxWidgets/StrengthMeter.h

The current algorithm for calculating password strength is quite simple.
Note: Files src/ui/wxWidgets/StrengthMeter.h and src/ui/wxWidgets/StrengthMeter.cpp have been added.
Resolves #1237

[wx] Add password strength meter to Add/Edit dialog

---

src/core/Util.cpp

Catches intermittent errors like when reading from network or cloud storage

Check return value of fread for errors

---

install/windows/pwsafe.wxs
src/ui/Windows/I18N/pos/pwsafe_ar.po
src/ui/Windows/I18N/pos/pwsafe_cz.po
src/ui/Windows/I18N/pos/pwsafe_de.po
src/ui/Windows/I18N/pos/pwsafe_dk.po
src/ui/Windows/I18N/pos/pwsafe_es.po
src/ui/Windows/I18N/pos/pwsafe_fr.po
src/ui/Windows/I18N/pos/pwsafe_hu.po
src/ui/Windows/I18N/pos/pwsafe_it.po
src/ui/Windows/I18N/pos/pwsafe_kr.po
src/ui/Windows/I18N/pos/pwsafe_lv.po
src/ui/Windows/I18N/pos/pwsafe_nl.po
src/ui/Windows/I18N/pos/pwsafe_pl.po
src/ui/Windows/I18N/pos/pwsafe_pt_br.po
src/ui/Windows/I18N/pos/pwsafe_ru.po
src/ui/Windows/I18N/pos/pwsafe_sk.po
src/ui/Windows/I18N/pos/pwsafe_sl.po
src/ui/Windows/I18N/pos/pwsafe_sv.po
src/ui/Windows/I18N/pos/pwsafe_tr.po
src/ui/Windows/I18N/pos/pwsafe_zh.po
src/ui/Windows/I18N/pwsafe.pot
src/ui/Windows/OptionsMisc.cpp
src/ui/Windows/res/PasswordSafe3.rc2
src/ui/Windows/resource3.h

Fixes #1525 by replacing "Select Browser:" with "Select Program"
applied to all supported translations.

BR1525 wrong title bar in "Select Browser" when selecting alt. text editor

---

install/windows/pwsafe.wxs
src/ui/Windows/MainView.cpp

BR1524 fix view reports names

---

src/ui/Windows/MainEdit.cpp

An improvement, but still needs work for the case where only a dependent entry (alias or shortcut) is dropped without it's corresponding base. That will be addressed in a separate PR.

Dnd assert fix

---

docs/ReleaseNotes.md
src/ui/Windows/MainView.cpp
version.mfc

Report selection for non-English languages via toolbar
Fixes #1531

[GH1531] Followup on GH1524 

---

src/ui/wxWidgets/I18N/pos/pwsafe_da.po
src/ui/wxWidgets/I18N/pos/pwsafe_de.po
src/ui/wxWidgets/I18N/pos/pwsafe_es.po
src/ui/wxWidgets/I18N/pos/pwsafe_fr.po
src/ui/wxWidgets/I18N/pos/pwsafe_hu.po
src/ui/wxWidgets/I18N/pos/pwsafe_it.po
src/ui/wxWidgets/I18N/pos/pwsafe_ko.po
src/ui/wxWidgets/I18N/pos/pwsafe_nl.po
src/ui/wxWidgets/I18N/pos/pwsafe_pl.po
src/ui/wxWidgets/I18N/pos/pwsafe_ru.po
src/ui/wxWidgets/I18N/pos/pwsafe_sk.po
src/ui/wxWidgets/I18N/pos/pwsafe_sl.po
src/ui/wxWidgets/I18N/pos/pwsafe_sv.po
src/ui/wxWidgets/I18N/pos/pwsafe_zh.po
src/ui/wxWidgets/I18N/pwsafe.pot
src/ui/wxWidgets/MenuEditHandlers.cpp
src/ui/wxWidgets/MenuFileHandlers.cpp

Addresses https://github.com/pwsafe/pwsafe/issues/1552 and https://github.com/pwsafe/pwsafe/issues/1554 (po files updated with machine translations).

Ronys wx i18n tweaks

---

src/ui/wxWidgets/MenuFileHandlers.cpp

[wx] Fix MRU list as suggested by froggie2523

---

help/default/html/edit_menu.html
help/default/html/file_menu.html
src/ui/wxWidgets/HelpMap.h
src/ui/wxWidgets/SafeCombinationChangeDlg.cpp

[wx] Various dialog help updates

---

src/ui/Windows/I18N/pos/pwsafe_sk.po
src/ui/wxWidgets/I18N/pos/pwsafe_sk.po

Please confirm these minor changes to Slovak translation on Windows.

[i18n win] Updates to Slovak .PO file

---

src/ui/Windows/AddEdit_Basic.cpp
src/ui/wxWidgets/AddEditPropSheetDlg.cpp

Resolves #1562 for both Windows and wxWidgets

Gh1562 alias shortcut error handling

---

Xcode/pwsafe-xcode6.xcodeproj/project.pbxproj
src/os/mac/media.cpp

[macOS] CFStringGetCStringPtr can return NULL

---

src/ui/wxWidgets/ViewReportDlg.cpp

[GH1557] Sanitize report texts before display

---

.github/workflows/macos-latest.yml

[macOS] Correct variable name in workflow

---

.github/workflows/macos-cmake-latest.yml

Bump XCODE_VER in macos-cmake-latest.yml workflow

---

src/os/unix/PWYubi.cpp

Make sure m_ykerrstr is set if no YubiKey inserted
